alibaba/rax

- package.json
- packages/universal-jsonp/src/__tests__/index.web.js
> fix: test error

- scripts/link.js
See failed test job https://travis-ci.org/alibaba/rax/jobs/191275579
> fix: multiple dependency on test

- README.md
ref: https://github.com/alibaba/weex/issues/2253
> docs: update the weex logo

- README.md
> Change the wrong toast link

- packages/element-loader/README.md
- packages/element-loader/package.json
- packages/element-loader/src/index.js
- packages/element-loader/src/node-loader.js
- packages/element-loader/src/template-loader.js
Add script compiler
```html
<script>
export default class extends Component {
constructor(props) {
console.log(props);
}
componentWillMount() {
this.customMethod();
console.log('will mount', this);
}
componentDidMount() {
console.log('did mount', this);
}
customMethod() {
console.log('custom');
}
}
</script>
```
> Add element loader script compiler

- README.md
> docs/readme: copyedit

- packages/stylesheet-loader/src/Validation.js
- packages/stylesheet-loader/src/index.js
- packages/stylesheet-loader/src/promptMessage.js
- packages/stylesheet-loader/src/transformer.js
In order to enhance the friendly interaction output warning and error information during the development.
> Add browser prompt message in development

- packages/runtime-shared/src/matchMedia.js
- packages/web-rax-framework/src/index.js
- packages/weex-rax-framework/src/index.js
- scripts/dist.js
add matchMedia method to follow [w3c](https://drafts.csswg.org/cssom-view/#dom-window-matchmedia)
> Add global matchMedia method

- packages/rax/src/vdom/instance.js
Text has no method `hasAttribute`.
> Fix no hasAttribute method in web

- packages/stylesheet-loader/README.md
- packages/stylesheet-loader/src/index.js
> Stylesheet loader add media rule

- packages/stylesheet-loader/src/PropTypes.js
- packages/stylesheet-loader/src/Validation.js
- packages/stylesheet-loader/src/index.js
* Warning when css property is not specification (eg. float、zIndex...)
* Fix error warning syntax
* Not output empty message
> Add warning when not specification property

- packages/stylesheet-loader/README.md
- packages/stylesheet-loader/src/index.js
- packages/stylesheet-loader/src/transformer.js
```css
.container:active {
background-color: red;
}
```
ref <https://github.com/alibaba/weex/pull/2115>
> Add pseudo class in weex

- packages/stylesheet-loader/src/__tests__/transformer.js
- packages/stylesheet-loader/src/index.js
- packages/stylesheet-loader/src/transformer.js
1. Can add comment in css file
```css
/* container style */
.container {
/* width must be 750 */
width: 750;
}
```
2. Fix console error when value adds quote 
```css
.containerTitle {
color: 'red'
}
```
> Can add comment in css file

- packages/universal-env/README.md
- packages/universal-jsonp/README.md
- packages/universal-panresponder/README.md
- packages/universal-platform/README.md
- packages/universal-toast/README.md
- packages/universal-transition/README.md
> Perfect universal docs

- packages/rax-webpack-plugin/src/index.js
- packages/web-rax-framework/src/index.js
Consistent web-rax-framework fontface api with weex-rax-framework fontface api.
> fix: fontface api

- packages/rax-cli/src/generator/templates/webpack.config.js
> Revert "fix: source-map should in comment block"

- packages/rax-components/src/RecyclerView.js
- packages/rax-components/src/ScrollView.js
- packages/rax-components/src/Text.js
- packages/rax-components/src/__tests__/RecyclerView.weex.js
- packages/rax/src/drivers/browser.js
> Feature components fix

- packages/babel-plugin-transform-jsx-stylesheet/package.json
- packages/babel-plugin-transform-jsx-stylesheet/src/__tests__/index.js
- packages/babel-plugin-transform-jsx-stylesheet/src/index.js
> Add transform-jsx-stylesheet testing

- packages/babel-plugin-transform-jsx-stylesheet/src/__tests__/index.js
> Fix node 4.8.0 test error

- packages/rax-link/src/__tests__/Link.js
- packages/rax-link/src/index.js
> fix: fix Link text can not inherit the styles props #140

- packages/rax-recyclerview/package.json
- packages/rax-switch/src/__tests__/Switch.js
- packages/rax-switch/src/index.js
> fix: switch setState keep one times & fix recyclerview package.json

- packages/rax-webpack-plugin/src/TraverseImport.js
- packages/rax-webpack-plugin/src/__tests__/TraverseImport.import.js
- packages/rax-webpack-plugin/src/__tests__/fixtures/bundle-compatible/expected/index.bundle.js
- packages/rax-webpack-plugin/src/__tests__/fixtures/bundle/expected/index.bundle.js
- packages/rax-webpack-plugin/src/__tests__/fixtures/factory-factoryGlobals/expected/index.factory.js
- packages/rax-webpack-plugin/src/__tests__/fixtures/factory/expected/index.factory.js
- packages/rax-webpack-plugin/src/__tests__/fixtures/function/expected/index.function.js
- packages/rax-webpack-plugin/src/__tests__/fixtures/module/expected/index.module.js
- packages/rax-webpack-plugin/src/__tests__/fixtures/umd/expected/index.umd.js
Input code:
`import * as env from 'universal-env';`
Output code: 
```js
const env = {
isWeex: true,
isWeb: false,
isNode: false,
isReactNative: false
};
```
> MultiplePlatform support Import namespace specifier

- packages/stylesheet-loader/README.md
- packages/stylesheet-loader/src/BoxModelPropTypes.js
- packages/stylesheet-loader/src/ColorPropTypes.js
- packages/stylesheet-loader/src/PropTypes.js
```css
.container {
width: 600;
height: 400;
padding: 50;
background-image: linear-gradient(to right, blue, white);
}
```
> Add background-image property

- packages/rax-cli/bin/rax.js
- packages/rax-cli/package.json
- packages/rax-cli/src/generator/index.js
- packages/rax-cli/src/generator/templates/package.json
- packages/rax-cli/src/generator/templates/public/index.html
- packages/rax-cli/src/index.js
- packages/rax-webpack-plugin/src/__tests__/fixtures/bundle-compatible/expected/index.bundle.js
- packages/rax-webpack-plugin/src/__tests__/fixtures/bundle/expected/index.bundle.js
- packages/rax-webpack-plugin/src/__tests__/fixtures/factory-factoryGlobals/expected/index.factory.js
- packages/rax-webpack-plugin/src/__tests__/fixtures/factory/expected/index.factory.js
- packages/rax-webpack-plugin/src/__tests__/fixtures/function/expected/index.function.js
- packages/rax-webpack-plugin/src/__tests__/fixtures/module/expected/index.module.js
- packages/rax-webpack-plugin/src/__tests__/fixtures/umd/expected/index.umd.js
fix #151 
修复以下：
- rax init demo，按 ctrl+c 报错  
- ~~npm 速度慢，暂时用 --registry=cnpm源~~
- prompt 改成  inquirer.js，替换 package.json 字段
- favicon
cc @noyobo
> fix: rax-cli improve user-experience

- packages/rax-animated/package.json
- packages/rax-animated/src/animated.js
- packages/rax-animated/src/createAnimatedComponent.js
ref <https://github.com/boiawang/animated-js/commit/39387087f75a7d6114af8843d851c3bb674cfe19>
> Use animated-js fix lint

- packages/rax-theme-taobao/README.md
- packages/rax-theme-taobao/package.json
- packages/rax-theme-zhihu/README.md
- packages/rax-theme-zhihu/package.json
> feat: add rax theme chat

- packages/weex-driver/src/elements/button.js
- packages/weex-driver/src/elements/index.js
```jsx
<button onClick={() => {alert(123)}}>默认按钮</button>
<button onClick={() => {alert(123)}} disabled>禁用按钮</button>
<button onClick={() => {alert(123)}} style={{
backgroundColor: '#f40',
color: '#fff',
fontSize: 60
}}>自定义按钮样式</button>
```
weex: 
web:
> feat: weex-driver support button

- packages/rax/package.json
> fix: add weex-driver to rax dep

- packages/rax-webpack-plugin/src/index.js
> fix: framework comment be removed by uglify

- packages/rax-animated/package.json
> fix: animted-js 0.0.4 for rax-animted

- examples/animated/index.html
- examples/animated/index.js
- packages/rax-animated/package.json
ref https://github.com/boiawang/animated-js/commit/6995f65607d7e43c65f5afc8b3b67f6f89a3e74b
> Fix animated without Set

- packages/stylesheet-loader/src/transformer.js
> Add css class syntax

- README.md
- docs/en-US/driver-spec.md
> docs: fix link address

- docs/zh-Hans/component/list-view.md
- docs/zh-Hans/component/recycler-view.md
- docs/zh-Hans/component/scroll-view.md
- packages/rax-recyclerview/src/index.js
- packages/rax-scrollview/src/index.js
- use same scroll event content in web and weex
- update docs
> feat: use same scroll event content in web and weex

- packages/rax-grid/src/Col.js
- packages/rax-picker/src/index.js
- packages/rax-scrollview/src/index.js
> Fix rax component fix

- docs/zh-Hans/component/calendar.md
- docs/zh-Hans/component/checkbox.md
- docs/zh-Hans/component/gotop.md
- docs/zh-Hans/component/grid.md
- packages/rax-button/README.md
- packages/rax-calendar/README.md
- packages/rax-checkbox/README.md
- packages/rax-countdown/README.md
- packages/rax-datepicker/README.md
- packages/rax-gotop/README.md
- packages/rax-grid/README.md
- packages/rax-icon/README.md
- packages/rax-image/README.md
- packages/rax-link/README.md
- packages/rax-listview/README.md
> Doc component readme

- packages/rax-listview/src/__tests__/ListView.js
- packages/rax-listview/src/index.js
- packages/rax-recyclerview/src/__tests__/RecyclerView.weex.js
- packages/rax-recyclerview/src/index.js
- packages/rax-scrollview/package.json
- packages/rax-scrollview/src/index.js
> Fix rax components

- packages/rax-countdown/src/index.js
> fix: fix seconds num in countdown

- packages/rax-scrollview/src/index.js
- packages/rax-tabheader/src/AnimBuoy.js
- packages/rax-tabheader/src/Item.js
- packages/rax-tabheader/src/ItemList.js
> fix: fix null child in scrollview

- packages/stylesheet-loader/src/BoxModelPropTypes.js
- packages/stylesheet-loader/src/index.js
1. add transform  property
2. fix media query error
> Enhance stylesheet

- packages/universal-platform/src/index.js
fix: use lowercase platform name
> fix: use lowercase platform name

- packages/rax-menulist/src/MenuItem.js
- packages/rax-menulist/src/index.js
* fix border width in web
* add default visible value
* fix transition error
> fix menulist style & transition error

- .editorconfig
- .eslintrc.js
- packages/rax-webpack-plugin/src/RaxMainTemplatePlugin.js
- packages/runtime-shared/src/symbol.js
- packages/runtime-shared/src/weakmap.js
* add editorconfig
* add no-tabs and no-mixed-spaces-and-tabs rule
> feat: update lint rule

- packages/webgl-driver/README.md
- packages/webgl-driver/package.json
- packages/webgl-driver/src/components/cameras/PerspectiveCamera.js
- packages/webgl-driver/src/components/controls/OrbitControls.js
- packages/webgl-driver/src/components/controls/TrackballControls.js
- packages/webgl-driver/src/components/core/BufferGeometry.js
- packages/webgl-driver/src/components/core/Geometry.js
- packages/webgl-driver/src/components/core/Object3D.js
- packages/webgl-driver/src/components/core/Raycaster.js
- packages/webgl-driver/src/components/geometries/BoxGeometry.js
- packages/webgl-driver/src/components/geometries/CylinderGeometry.js
- packages/webgl-driver/src/components/geometries/SphereGeometry.js
- packages/webgl-driver/src/components/index.js
- packages/webgl-driver/src/components/lights/AmbientLight.js
- packages/webgl-driver/src/components/lights/DirectionalLight.js
- packages/webgl-driver/src/components/materials/LineBasicMaterial.js
- packages/webgl-driver/src/components/materials/LineDashedMaterial.js
- packages/webgl-driver/src/components/materials/MeshBasicMaterial.js
- packages/webgl-driver/src/components/materials/MeshLambertMaterial.js
- packages/webgl-driver/src/components/materials/MeshPhongMaterial.js
- packages/webgl-driver/src/components/materials/PointsMaterial.js
- packages/webgl-driver/src/components/objects/Line.js
- packages/webgl-driver/src/components/objects/Mesh.js
- packages/webgl-driver/src/components/objects/Points.js
- packages/webgl-driver/src/components/scenes/Scene.js
- packages/webgl-driver/src/createElement.js
- packages/webgl-driver/src/driver.js
- packages/webgl-driver/src/index.js
- packages/webgl-driver/src/plugin/controls/OrbitControls.js
- packages/webgl-driver/src/plugin/controls/TrackballControls.js
> feat: add webgl driver

- packages/rax-theme-buy/README.md
- packages/rax-theme-buy/package.json
- packages/rax-theme-buy/public/index.html
- packages/rax-theme-buy/templates/default/App.css
- packages/rax-theme-buy/templates/default/App.js
- packages/rax-theme-buy/templates/default/index.js
- packages/rax-theme-buy/templates/default/mods/CardItem.js
- packages/rax-theme-buy/templates/default/mods/Counter.js
- packages/rax-theme-buy/templates/default/mods/FormLine.js
- packages/rax-theme-buy/templates/default/mods/FormSub.js
- packages/rax-theme-buy/webpack.config.js
> Feat rax theme buy

- docs/zh-Hans/component/multirow.md
- docs/zh-Hans/component/picture.md
- packages/rax-modal/README.md
- packages/rax-multirow/README.md
- packages/rax-picker/README.md
- packages/rax-picture/README.md
> feat: add readme for components

- packages/babel-plugin-transform-jsx-stylesheet/src/__tests__/index.js
- packages/babel-plugin-transform-jsx-stylesheet/src/index.js
```js
import { createElement, Component } from 'rax';
import './app.css';
class App extends Component {
render() {
return <div className="header" style={{
height: 100
}} />;
}
}
```
> Feat: add ObjectExpression type

- packages/weex-rax-framework/src/index.js
> fix: error when missing bundleUrl

- packages/babel-plugin-transform-jsx-stylesheet/src/__tests__/index.js
- packages/babel-plugin-transform-jsx-stylesheet/src/index.js
eg.
```js
import { createElement, render } from 'rax';
import './app.css';
render(<div className="header" />);
```
> Feat: supports writing constant JSX in render

- packages/rax-tabbar/src/TabBarContents.js
content of each tab need a container, the container is layout, and component should not change user's style
> fix(component): this.props.children could be any type, .length is wrong condition

- packages/rax-slider/src/index.js
- packages/rax-slider/src/slider.web.js
> fix slideTo in slider

- packages/rax-modal/src/index.js
- packages/rax-textinput/src/index.js
> fix textinput & modal

- examples/hello/index.js
- packages/rax-image/src/index.js
- packages/rax-link/src/index.js
- packages/rax-text/src/index.js
https://github.com/alibaba/rax/issues/285
> feat: rax-text support nested children

- packages/rax-picture/src/optimizer/compress.js
- packages/rax-picture/src/optimizer/index.js
- packages/rax-picture/src/optimizer/isCdnImage.js
- packages/rax-picture/src/optimizer/removeScheme.js
- packages/rax-picture/src/optimizer/replaceDomain.js
- packages/rax-picture/src/optimizer/scaling.js
- packages/rax-picture/src/optimizer/webp.js
- packages/rax-picture/src/picture.web.js
- packages/rax-picture/src/picture.weex.js
> cdn picture optimizer for ali url

- packages/rax-webpack-plugin/src/__tests__/fixtures/bundle-compatible/expected/index.bundle.js
- packages/rax-webpack-plugin/src/__tests__/fixtures/bundle/expected/index.bundle.js
- packages/rax-webpack-plugin/src/__tests__/fixtures/cmd/expected/index.cmd.js
- packages/rax-webpack-plugin/src/__tests__/fixtures/custom/expected/index.bundle.js
- packages/rax-webpack-plugin/src/__tests__/fixtures/factory-factoryGlobals/expected/index.factory.js
- packages/rax-webpack-plugin/src/__tests__/fixtures/factory/expected/index.factory.js
- packages/rax-webpack-plugin/src/__tests__/fixtures/function/expected/index.function.js
- packages/rax-webpack-plugin/src/__tests__/fixtures/module/expected/index.module.js
- packages/rax-webpack-plugin/src/__tests__/fixtures/umd/expected/index.umd.js
- packages/rax-webpack-plugin/src/__tests__/index.js
Update rax-webpack-plugin test fixture command: 
```
RAX_FIXTURE=WEBPACK_PLUGIN npm test -- ./packages/rax-webpack-plugin/src/__tests__/index.js
```
> test: update rax-webpack-plugin test fixtures

- packages/rax-text/src/index.js
> fix: variable reference

- packages/rax-counter/src/index.js
- packages/rax-gotop/src/index.js
- packages/rax-link/src/index.js
- packages/rax-recyclerview/src/index.js
- packages/rax-textinput/src/index.js
> Fix components

- packages/rax-recyclerview/src/index.js
> fix: first child can be null in listview header

- docs/zh-Hans/guide/event-handle.md
> fix: loadmoreoffset explanation

- packages/universal-transition/package.json
- packages/universal-transition/src/index.js
> rem单位处理，callback不执行bugfix

- docs/zh-Hans/component/chart-pie.md
- packages/rax-charts/src/chart/Pie.js
> fix(rax-charts): 修复rax-charts的color属性不支持多参数的问题

- packages/weex-rax-framework/src/index.js
> feat: add __weex_config__ for js service

- packages/rax-slider/src/slider.web.js
> fix: rax-slider loop not work on web

- packages/rax/package.json
> fix: fix-rax-packagejson

- packages/rax/src/children.js
- toArray should filter null value
> fix: children api

- scripts/dist.js
rax-dom's globalName should be RaxDOM not RaxDom, `uppercamelcase` works not well
> chore: dist compile globalName

- packages/web-rax-framework/src/appear.js
- packages/web-rax-framework/src/appearRegistry.js
没有 IntersectionObserver 的情况，首次渲染复杂页面速度快了一倍
> chore: 优化 appear 性能

- packages/rax-recyclerview/src/index.js
> fix: child.props in recyclerview

- packages/weex-rax-framework/src/index.js
> feat: remove updateFinish in framework

- packages/rax-cli/src/generator/templates/public/index.html
> update framework url

- packages/driver-browser/src/__tests__/flexbox.js
- packages/driver-browser/src/flexbox.js
> fix: webkitFlexWrap for android

- packages/weex-rax-framework/src/location.weex.js
Android 下如果不传默认值，在Native 的一些场景下会报错，希望可以加一个默认值
> 增加reload 默认值

- packages/rax-scrollview/package.json
- packages/rax-scrollview/src/index.js
fix the scrollTo function with an animation  effect in browser
> fix the scrollTo function with an animation  effect in browser

- packages/style-unit/src/index.js
- packages/universal-transition/src/index.js
> fix: web setRem error in cmd bundle

- packages/driver-server/README.md
just fix driver-server/readme.md
> fix doc of driver-server

- docs/zh-Hans/component/picture.md
- packages/rax-picture/src/picture.web.js
之前的逻辑只判断了this.uri是否有被赋值过，应该增加forceupdate的判断
> 给piture组件添加forceupdate判断

- package.json
- packages/template-buy/package.json
- packages/template-buy/webpack.config.js
- packages/template-chat/package.json
- packages/template-chat/webpack.config.js
- packages/template-retail/package.json
- packages/template-retail/webpack.config.js
- packages/template-taobao/package.json
- packages/template-taobao/webpack.config.js
- packages/template-zhihu/package.json
- packages/template-zhihu/webpack.config.js
- scripts/dist.js
> Fix build dist

- docs/zh-Hans/guide/panresponder.md
这个手势在playGround上跑不了，我修改一下，可以跑了~
> 解决panresponder文档demo在playGround跑不动

- packages/element-loader/README.md
> docs: fix some element loader typo

- packages/rax-scrollview/package.json
> fix: update animation-util

- packages/rax-scrollview/src/index.js
in rax  server side render, rax-scrollview's render function has throw some error.
> rax-scrollview in nodejs env will throw document is undefined

- packages/driver-browser/src/index.js
- packages/driver-server/src/index.js
> fix: EVENT_PREFIX_REGEXP in driver-browser & driver-server

- packages/universal-transition/src/index.js
> Fix universal transition need layout

- packages/babel-plugin-transform-jsx-stylesheet/README.md
- packages/babel-plugin-transform-jsx-stylesheet/package.json
- packages/babel-plugin-transform-jsx-stylesheet/src/__tests__/index.js
- packages/babel-plugin-transform-jsx-stylesheet/src/index.js
See <https://github.com/alibaba/rax/issues/433>
> feat: className supports array, object and expressions

- examples/components/TabPanelDemo.js
- examples/components/index.js
- package.json
- packages/rax-tab-panel/package.json
- packages/rax-tab-panel/src/BaseView.js
- packages/rax-tab-panel/src/DefaultView.js
- packages/rax-tab-panel/src/Detection.js
- packages/rax-tab-panel/src/PanView.js
- packages/rax-tab-panel/src/SliderView.js
- packages/rax-tab-panel/src/TabController.js
- packages/rax-tab-panel/src/TabPanel.js
- packages/rax-tab-panel/src/TabPanelLink.js
- packages/rax-tab-panel/src/TabPanelView.js
- packages/rax-tab-panel/src/Utils.js
- packages/rax-tab-panel/src/__tests__/TabPanel.js
- packages/rax-tab-panel/src/index.js
> feat: add rax-tab-panel component

- packages/universal-env/src/index.js
- templates/template-buy/package.json
- templates/template-chat/package.json
- templates/template-retail/package.json
- templates/template-taobao/package.json
- templates/template-zhihu/package.json
> fix: use typeof WXEnvironment for Vue Weex

- packages/rax-tab-panel/src/DefaultView.js
fix horizontal pan trigger switchTo function on web.
> fix: fix panend trigger render

- packages/babel-plugin-transform-jsx-stylesheet/package.json
- packages/babel-plugin-transform-jsx-stylesheet/src/index.js
Fix <https://github.com/alibaba/rax/issues/450>
> Fix babel plugin transform jsx stylesheet

- packages/babel-plugin-transform-jsx-stylesheet/README.md
- packages/babel-plugin-transform-jsx-stylesheet/package.json
- packages/babel-plugin-transform-jsx-stylesheet/src/__tests__/index.js
- packages/babel-plugin-transform-jsx-stylesheet/src/index.js
`className` 传入对象时报错
```
<View className={{ container: true }} /> 
```
> fix: classname with object

- packages/driver-worker/src/create-document.js
- packages/driver-worker/src/dom-renderer.js
> Add canvas element

- packages/rax-recyclerview/src/index.js
- packages/rax-scrollview/src/index.js
见 issue <https://github.com/alibaba/rax/issues/462>
> fix: 修复ScrollView和RecyclerView的onScroll事件参数不包含contentSize的问题

- packages/driver-browser/src/index.js
> Feat svg support

- packages/driver-worker/src/create-document.js
> Fix: canvas element 传递 propertyValues 时需要做浅拷贝

- packages/universal-jsonp/src/index.js
> feat: add dataType for miniapp (universal-jsonp)

- packages/rax-image/README.md
- packages/rax-image/src/index.js
>  fix/rax-image: 修正使其在图片加载失败时能够正确执行错误处理函数，并使用默认图片替代

- packages/rax-countdown/README.md
- packages/rax-countdown/src/index.js
The PR contains both bug fixed and correspondding README file updated. More details can be found at #503 .
> Fix rax countdown tpl bug

- packages/universal-transition/src/index.js
> Fix: node sometimes is null in web

- packages/rax-scripts/package.json
- packages/rax-scripts/src/config/webpack.config.base.js
> feat: add sfc-loader support

- packages/rax-player/src/progresspoint.js
> fix: player progressBar in h5

- packages/rax-modal/src/index.js
修正modal在父组件通过state管控visible状态时，初始化的visibilty为hidden而不显示的bug
> fix: 修复modal默认受控状态下visibility为hidden

- packages/rax-image/src/index.js
> 赋能image组件，对外暴露save方法，以方便业务方使用保存图片到本地的能力

- packages/driver-worker/src/dom-renderer.js
- packages/driver-worker/src/index.js
触摸系事件, 增加 evt.touches 和 evt.changedTouches 对象的传递
> feat: [driver-worker] add touches support

- scripts/dist-components.js
- scripts/dist-packages.js
> Revert "Feat build jsservice"

- package.json
- scripts/dist-builtins.js
> Feat build jsservice

- babel.config.js
- package.json
> feat: use babel-plugin-add-module-exports

- components/rax-slider/src/index.js
- packages/universal-platform/src/__tests__/index.js
> fix: rax-slider SliderWeb.default is undefined

- components/rax-listview/src/index.d.ts
修改rax-listview的ts可选参数配置，可选参数增加?
> 修改rax-listview的ts可选参数配置

- packages/atag/src/components/input/index.html
- packages/atag/src/components/switch/index.html
- packages/atag/tests/webpack.test.js
> fix: input & switch bug

- packages/atag/src/components/navigator/index.html
- packages/atag/src/components/video/video.native.js
> fix: video & navigator

- packages/atag/src/components/audio/index.html
> fix: atag audio

- packages/atag/src/components/checkbox-group/index.html
- packages/atag/src/components/checkbox/index.html
> fix: checkbox style

- packages/atag/src/components/form/index.html
- packages/atag/src/components/progress/index.html
- packages/atag/src/components/radio-group/index.html
- packages/atag/src/components/radio/index.html
- packages/atag/src/components/scroll-view/index.html
- packages/atag/src/components/slider/index.html
- packages/atag/src/components/switch/index.html
- packages/atag/src/components/view/index.html
> fix: remove redundant code

- packages/atag/src/components/video/video.web.js
> fix: video style

- packages/atag/src/components/picker-view/index.html
- packages/atag/src/components/picker-view/picker-view-column.html
- packages/atag/src/components/video/video.web.js
> fix: atag picker-view

- packages/atag/src/components/input/index.html
- packages/atag/src/components/textarea/index.html
> fix: input & textarea compatible ios8

- packages/atag/src/components/audio/index.html
- packages/atag/src/components/button/index.html
- packages/atag/src/components/checkbox/index.html
- packages/atag/src/components/input/index.html
- packages/atag/src/components/picker-view/index.html
- packages/atag/src/components/picker-view/picker-view-column.html
- packages/atag/src/components/picker/index.html
- packages/atag/src/components/progress/index.html
- packages/atag/src/components/radio/index.html
- packages/atag/src/components/slider/index.html
- packages/atag/src/components/swiper/index.html
- packages/atag/src/components/swiper/swiper-item.html
- packages/atag/src/components/textarea/index.html
- packages/atag/src/components/video/video.web.js
> fix: atag flex compatible ios8

- packages/atag/demo/index.htm
- packages/atag/src/components/button/index.html
- packages/atag/src/components/input/index.html
- packages/atag/src/components/picker-view/index.html
- packages/atag/src/components/picker-view/picker-view-column.html
- packages/atag/src/components/picker/index.html
- packages/atag/src/components/swiper/index.html
- packages/atag/src/components/switch/index.html
- packages/atag/src/components/textarea/index.html
> fix: atag css3 compatible ios8 & fix picker-view scroll bug

- components/rax-gesture-view/package.json
- components/rax-gesture-view/src/gesture.web.js
- components/rax-gesture-view/src/gesture.weex.js
- components/rax-gesture-view/src/index.js
- docs/zh-Hans/component/gesture-view.md
- examples/components/package.json
- examples/components/public/index.html
- examples/components/src/GestureViewDemo.js
- examples/components/src/index.js
- package.json
- packages/atag/src/components/image/index.js
- packages/atag/src/components/video/video.web.js
onHorizontalPan onVerticalPan support
> feat: add gesture-view

- packages/atag/src/components/audio/index.html
- packages/atag/src/components/swiper/index.html
> fix: swiper indicator-dots default is false

- packages/atag/demo/index.htm
- packages/atag/src/components/scroll-view/index.html
- packages/atag/src/components/switch/index.html
> fix: scroll-view scroll-into-view's bug

- packages/atag/demo/index.htm
- packages/atag/src/components/textarea/index.html
> feat: fix textarea bug & add show-count

- packages/rax/src/vdom/__tests__/fragment.js
- packages/rax/src/vdom/native.js
**核心diff算法bug**
当dom元素走更新的时候，fragment情况下，出现倒序bug
[demo地址](https://codepen.io/anon/pen/ZMoWLJ)
> fix: diff error when update

- packages/rax/src/vdom/__tests__/key.js
- packages/rax/src/vdom/native.js
**diff算法核心bug**
当两个元素的key相同，但是类型不(不走更新)的时候，之前的算法中仅仅是做旧dom和新dom的替换，没有移动位置，导致出现bug
[demo地址](https://codepen.io/anon/pen/EeLPzv)
> fix: render error for diff type element with same key

- packages/atag/src/components/image/index.html
- packages/atag/src/components/textarea/index.html
> fix: image & textarea

- packages/driver-worker/package.json
- packages/driver-worker/src/create-document.js
- packages/driver-worker/src/dom-renderer.js
如果全部判断 typeof boolean 对整体影响很大, 白名单模式添加进来
> feat: driver worker bool property

- packages/atag/src/components/swiper/index.html
> hotfix: set current dynamically

- packages/atag/src/components/scroll-view/index.html
- packages/atag/src/components/switch/index.html
> fix: scroll-view scrollIntoView

- packages/atag/demo/index.htm
- packages/atag/src/components/checkbox/index.html
- packages/atag/src/components/radio-group/index.html
- packages/atag/src/components/radio/index.html
- packages/atag/src/components/textarea/index.html
> fix: checkbox & radio checked

- packages/atag/src/components/checkbox/index.html
- packages/atag/src/components/image/index.html
- packages/atag/src/components/input/index.html
- packages/atag/src/components/label/index.html
- packages/atag/src/components/radio-group/index.html
- packages/atag/src/components/radio/index.html
- packages/atag/src/components/textarea/index.html
> fix: label bug & input/textarea text-align

- packages/atag/src/components/button/index.html
- packages/atag/src/components/checkbox/index.html
- packages/atag/src/components/slider/index.html
- packages/atag/src/components/textarea/index.html
> fix: checked event propagation & button

- packages/atag/src/components/swiper/index.html
> fix: swiper vertical style & touchmove bug

- packages/atag/src/components/swiper/index.html
while touchstart, transition: 0s; touchend to restore
> fix: atag swiper should deafult to transition 500ms

- packages/atag/src/shared/gestures.js
- packages/mp-loader/package.json
- packages/mp-runtime/package.json
- packages/mp-runtime/src/createPage.js
1. 生命周期矫正: ref https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/page.html#%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F
- onLoad 中 setData 可以直接调用, onLoad 中setData 的callback 回调正确执行
- onLoad -> onShow -> onReady 时序问题修复
2. 修复 setData 未传值时报错问题
> Fix mp runtime

- packages/atag/src/components/button/index.html
> feat: button custom style

- packages/mp-loader/package.json
- packages/mp-loader/src/index.js
- packages/mp-loader/src/page.js
- packages/mp-loader/src/template.js
- packages/mp-loader/src/transpiler/transpileModules/index.js
- packages/mp-loader/src/transpiler/transpileModules/web-view.js
- packages/mp-runtime/package.json
- packages/mp-runtime/src/createPage.js
feat: support `web-view` tag for mp
> feat: mini program support web-view

- packages/atag/src/components/input/index.html
- packages/atag/src/components/textarea/index.html
> fix: input/textarea default style

- packages/atag/package.json
- packages/mp-runtime/package.json
- packages/sfc-loader/package.json
- packages/sfc-runtime/package.json
- templates/template-buy/package.json
- templates/template-chat/package.json
- templates/template-retail/package.json
- templates/template-taobao/package.json
- templates/template-zhihu/package.json
webpack's update cause ci issues
ref. https://github.com/webpack/webpack/issues/8082
update webpack-cli to latest v3 to solve
> fix: update webpack-cli to avoid broken build

- packages/atag/demo/index.htm
- packages/atag/src/components/image/index.html
> fix: image render & widthFix switch

- packages/atag/src/components/image/index.js
- packages/atag/src/components/swiper/index.html
- packages/atag/src/components/video/video.native.js
> Refactor atag

- packages/miniapp-builder/src/config/getAppConfig.js
- packages/miniapp-builder/src/config/getFrameworkCDNUrl.js
- packages/miniapp-builder/src/server/controllers/bundle.js
> fix: rendererUrl by ctx

- packages/miniapp-builder/src/builder/tasks/buildConfig.js
- packages/miniapp-builder/src/config/getAppConfig.js
> Miniapp builder

- packages/rax/src/hydrate.js
> style: remove-useless-semi

- components/rax-touchable/src/index.js
> enhance(rax-touchable): 去除在web下的点击高亮显示，和weex保持一致

- packages/mp-loader/src/template.js
- packages/sfc-runtime/src/adapterComponent.js
- packages/sfc-runtime/src/convertComponentsDefining.js
- packages/sfc-runtime/src/getGlobalComponents.js
- packages/sfc-runtime/src/host.js
- packages/sfc-runtime/src/index.js
- packages/sfc-runtime/src/initWatch.js
- packages/sfc-runtime/src/lifecyclesMap.js
- packages/sfc-runtime/src/mixinData.js
- packages/sfc-runtime/src/mixinProps.js
- packages/sfc-runtime/src/sfc.js
- packages/sfc-runtime/src/store.js
- packages/sfc-runtime/src/vdom/createElement.js
- packages/sfc-runtime/src/vdom/index.js
- packages/sfc-runtime/src/vdom/setRuntime.js
重构 SFC-RUNTIME
1. 增加 SFC 变量, 后面有机会可以复用 Vue 的社区生态(Vuex, VueRouter 等...)
1.1 增加 use 接口
2. 适配 SFC2MP 
3. 其它不合理处改造
> Refactor sfc runtime

- packages/universal-jsonp/src/index.js
catch network failure and let us know outside in universal-jsonp
> fix: catch network failure and reject promise

- packages/driver-worker/src/dom-renderer.js
> fix: driver worker tag name to lower

- packages/driver-worker/package.json
- packages/driver-worker/src/index.js
- packages/style-unit/src/index.js
解决半像素下浏览器渲染的问题
- 参考支付宝小程序: 向下取整
> refactor: make driver worker pixel to floor

- packages/atag/demo/index.htm
- packages/atag/src/components/picker-view/index.js
- packages/atag/src/components/picker-view/picker-view-column.js
- packages/atag/src/components/picker/index.html
> refactor: rework picker-view for support pc

- packages/sfc2mp/package.json
> feat: sfc2mp upgrade sfc-runtime

- packages/atag/src/index.js
- packages/driver-worker/src/renderer/nodes.js
> chore: use unknown tag

- packages/miniapp-builder/package.json
- packages/miniapp-builder/src/server/controllers/bundle.js
Feat: 构建器支持 devServer 启动打包 includeFiles 和 imageAssets
> Miniapp builder (dev-server feature)

- packages/atag/demo/index.htm
- packages/atag/package.json
- packages/atag/src/components/image/index.js
- packages/atag/src/components/map/map.native.js
- packages/atag/src/components/map/map.web.js
- packages/atag/src/components/scroll-view/index.js
- packages/atag/src/components/textarea/index.js
- packages/atag/src/components/unknown/index.js
- packages/atag/src/components/video/video.native.js
- packages/atag/src/shared/getEnvironmentObject.js
- packages/atag/src/shared/getFileSchemaPrefix.js
- packages/atag/src/shared/shouldDowngradeNativeView.js
1. image 组件兼容 native fs schema
2. scroll-view 组件根据规范重构, 修复 scroll-x 取值的问题(attr vs prop).  (星巴克项目兼容性回归)
3. native 地图组件 参数再联调
4. textarea 的 maxlength 支持传入 -1, 代表 infinite
> Refactor atag(image + scroll-view + map)

- packages/mp-loader/demo/webpack.config.js
- packages/mp-loader/package.json
> fix: mp-loader with miniapp builder

- packages/atag/src/components/swiper/index.js
> fix: remove debugger

- packages/rax/src/createRef.js
- packages/rax/src/index.js
- packages/rax/src/vdom/__tests__/ref.js
- packages/rax/src/vdom/ref.js
> feat: rax support createRef

- components/rax-picture/src/optimizer/compress.js
- components/rax-picture/src/optimizer/index.js
- components/rax-picture/src/optimizer/isOSSImage.js
- components/rax-picture/src/optimizer/replaceDomain.js
- components/rax-picture/src/optimizer/scaling.js
- components/rax-picture/src/optimizer/webp.js
- components/rax-player/src/video.weex.js
- components/rax-static-view/README.md
- components/rax-static-view/package.json
- components/rax-static-view/src/__tests__/View.js
- components/rax-static-view/src/__tests__/View.weex.js
- components/rax-static-view/src/index.d.ts
- components/rax-static-view/src/index.js
> Feat update rax components

- packages/mp-loader/src/transpiler/transpileModules/events.js
组件的事件传递的时候 会有问题, 只 lowercase 第一个子母
> fix: event name should not be all lowercased

- packages/driver-worker/src/Driver.js
- packages/driver-worker/src/WorkerDriver.js
- packages/driver-worker/src/worker/Document.js
- packages/driver-worker/src/worker/Node.js
- packages/mp-loader/src/component-loader.js
修复 a-if 与 Component (fragment) 一起使用的时候 无法正常渲染的问题
> Fix driver worker

- packages/sfc2mp/package.json
- packages/sfc2mp/src/config/vendors.js
- packages/sfc2mp/src/helpers/createApp.js
- packages/sfc2mp/src/helpers/createPage.js
- packages/sfc2mp/src/vendor.config.js
SFC 导出变量是 export default, 在小程序里需要使用 `.default` 引入
> fix: sfc2mp sfc requirement

- packages/mp-loader/src/component-loader.js
- packages/mp-loader/src/component-resolver.js
- packages/mp-loader/src/index.js
- packages/mp-loader/src/runtimeHelpers.js
- packages/mp-loader/src/template-loader.js
- packages/mp-runtime/src/componentsHub.js
- packages/mp-runtime/src/createComponent.js
- packages/mp-runtime/src/createPage.js
> Fix mp component recursion

- components/rax-xslider/src/mods/Slider.js
expose `stopAutoPlay` and `autoPlay` api
> expose api

- components/rax-player/src/video.web.js
> fix this issues https://github.com/alibaba/rax/issues/625

- .travis.yml
- README.md
- package.json
- packages/mp-loader/README.md
> docs: readme improve

- docs/zh-Hans/component/slider.md
`autoplayTimeout`  change to `autoPlayInterval`
> fix rax-slider doc mistake

- components/rax-player/src/video.web.js
- packages/mp-runtime/README.md
> add readme

- components/rax-slider/src/index.d.ts
> onChange may not required

- README.md
- examples/hello/package.json
- lerna.json
- package.json
- packages/rax-scripts/README.md
- packages/rax-scripts/bin/rax-scripts-build.js
- packages/rax-scripts/bin/rax-scripts-start.js
- packages/rax-scripts/package.json
- packages/rax-scripts/src/build.js
- packages/rax-scripts/src/config/babel.config.js
- packages/rax-scripts/src/config/miniapp/webpack.config.base.js
- packages/rax-scripts/src/config/miniapp/webpack.config.dev.js
- packages/rax-scripts/src/config/miniapp/webpack.config.prod.js
- packages/rax-scripts/src/config/webpack.config.base.js
- packages/rax-scripts/src/start.js
- packages/rax-scripts/src/utils/createWebpackCompiler.js
- packages/rax-scripts/src/utils/rewireWebpackConfig.js
- packages/sfc-loader/src/helpers/runtime.js
- packages/sfc-loader/src/index.js
> chore: upgrade rax-scripts

- packages/miniapp-builder/src/config/babelConfig.js
- packages/miniapp-builder/src/config/getMiniProgramConfig.js
- packages/miniapp-builder/src/server/views/master.ejs
- packages/mp-loader/src/template-loader.js
- packages/mp-loader/src/transpiler/transpileModules/attrs.js
> Fix miniapp builder

- packages/miniapp-builder/src/builder/tasks/buildSchema.js
- packages/miniapp-builder/src/config/getAppConfig.js
> fix: builder

- packages/driver-worker/src/renderer/index.js
> feat: add client width

- packages/atag/src/components/animation/Event.js
- packages/atag/src/components/animation/Timeline.js
- packages/atag/src/components/animation/index.js
> Fix: Animation 增加容错处理

- packages/driver-browser/src/index.js
> fix: add tagNamePrefix namespace

- packages/driver-browser/package.json
> v0.6.7 driver-browser

- .travis.yml
- package.json
> ci: only run on node v8 and v11

- packages/mp-loader/src/component-loader.js
- packages/mp-runtime/src/__tests__/component.js
- packages/mp-runtime/src/createComponent.js
- packages/mp-runtime/src/createPage.js
兼容组件和 Page 的实现
https://docs.alipay.com/mini/framework/develop-custom-component
> feat: compatible with mp component and page

- README.md
- packages/rax/src/__tests__/createContext.js
- packages/rax/src/__tests__/memo.js
- packages/rax/src/index.js
- packages/rax/src/memo.js
- packages/rax/src/vdom/reactivecomponent.js
> feat: add memo

- README.md
- packages/rax/src/__tests__/fragment.js
- packages/rax/src/fragment.js
- packages/rax/src/index.js
> feat: fragment component

- packages/rax/src/__tests__/forwardRef.js
- packages/rax/src/forwardRef.js
- packages/rax/src/memo.js
- packages/rax/src/vdom/composite.js
- packages/rax/src/vdom/reactive.js
> feat: forwardRef

- packages/miniapp-builder/bin/cli.js
> fix: resolve incoming dir for windows

- packages/atag/src/components/image/index.js
Async decoding image demo video: https://drive.google.com/file/d/0B5cKk7MxQ2LsUUotR3RuWUlpSXc/view
> performance: decode the image asynchronously

- packages/miniapp-builder/src/config/getMiniProgramConfig.js
- packages/miniapp-builder/src/config/getSFCConfig.js
> fix: iOS8 miniapp style

- packages/babel-plugin-transform-jsx-stylesheet/src/__tests__/index.js
- packages/babel-plugin-transform-jsx-stylesheet/src/index.js
> chore: add __class in development env

- packages/mp-runtime/src/createPage.js
Fire pullDownRefresh event by native.
> feat: add on pull down refresh

- packages/atag/src/components/map/index.js
- packages/atag/src/components/map/map.native.js
> fix: map routeConfig leading cycle

- packages/rax-redux/README.md
- packages/rax-redux/package.json
> fix: remove rax and redux in deps

- packages/rax-scripts/bin/rax-scripts-build.js
- packages/rax-scripts/src/config/babel.config.js
- packages/rax-scripts/src/config/miniprogram/webpack.config.prod.js
- packages/rax-scripts/src/config/path.config.js
> rax-scripts support build dest config

- packages/render-helpers/package.json
- packages/render-helpers/src/__tests__/__snapshots__/createElement.js.snap
- packages/render-helpers/src/__tests__/createElement.js
- packages/render-helpers/src/createElement.js
Finally got the trouble maker:
现象:
当数组类型数据作为属性绑定时候, 无论修改任何其它的属性, 都会触发数组变化, 从而导致组件接收到attribute/prop Changed渲染指令
> fix: array set data

- packages/render-helpers/src/__tests__/__snapshots__/renderList.js.snap
- packages/render-helpers/src/__tests__/__snapshots__/renderStyle.js.snap
- packages/render-helpers/src/__tests__/__snapshots__/toString.js.snap
- packages/render-helpers/src/__tests__/createElement.js
- packages/render-helpers/src/__tests__/createEmptyElement.js
- packages/render-helpers/src/__tests__/createNotImplWarn.js
- packages/render-helpers/src/__tests__/createTextElement.js
- packages/render-helpers/src/__tests__/renderList.js
- packages/render-helpers/src/__tests__/renderSlot.js
- packages/render-helpers/src/__tests__/renderStyle.js
- packages/render-helpers/src/__tests__/toString.js
- packages/render-helpers/src/createElement.js
- packages/render-helpers/src/createEmptyElement.js
- packages/render-helpers/src/createNotImplWarn.js
- packages/render-helpers/src/createTextElement.js
- packages/render-helpers/src/renderList.js
- packages/render-helpers/src/renderSlot.js
- packages/render-helpers/src/renderStyle.js
- packages/render-helpers/src/toString.js
> Tests render helpers

- packages/atag/src/components/animation/Event.js
- packages/atag/src/components/animation/Pan.js
- pan 事件增加 touch 节点的 translateX 和 translateY 以及 start 状态下的 translateX 和 translateY
有些动画需要实现在 touch 结束以后做某些事情(比如说 swiper 手势结束后需要确定滑到上一页还是下一页或者保持在当前页面)
```html
<animation event-type="pan" event-origin="slider-scale-container">
<view class="slider-scale-container">
<view
class="slider-box"
id="slider-scale-container"
style="position: absolute;transform: translateX(8)px;"
animation-style="{{containerAnimationStyle}}"
>
<view
class="slider-child slider-child-1"
animation-style="{{child1Style}}"
>
</view>
<view
class="slider-child slider-child-2"
style="transform: scale(0.9);"
animation-style="{{child2Style}}"
></view>
<view
class="slider-child slider-child-3"
style="transform: scale(0.9);"
animation-style="{{child3Style}}"
></view>
</view>
</view>
</animation>
```
```javascript
Page({
data: { …
```
> feat: add translateXY

- packages/atag/src/components/scroll-view/index.js
> fix: scroll view set scroll top/left at first time

- README.md
- packages/rax-scripts/package.json
- packages/rax-scripts/src/config/babel.config.js
> build: support dynamic import

- packages/rax-scripts/package.json
- packages/rax-scripts/src/config/webapp/webpack.config.base.js
> build: add fragment config

- packages/rax/src/__tests__/element.js
- packages/rax/src/vdom/composite.js
- packages/rax/src/vdom/host.js
> refactor: remove sandbox toggle in host

- docs/en-US/driver-spec.md
- packages/driver-dom/package.json
- packages/driver-dom/src/index.js
- packages/driver-server/package.json
- packages/driver-server/src/index.js
- packages/driver-webgl/package.json
- packages/driver-webgl/src/driver.js
- packages/driver-weex/package.json
- packages/driver-weex/src/index.js
- packages/rax/src/vdom/native.js
> refactor: not need removeAllEventListener in driver

- packages/driver-worker/src/worker/Node.js
> fix: mutate child apply to insert before too

- packages/rax-scripts/package.json
- packages/rax-scripts/src/config/miniprogram/webpack.config.base.js
- packages/rax-scripts/src/config/webpackDevServer.config.js
* dev 阶段开启 disableHostCheck 便于本地代理调试
* miniapp h5 支持通过绝对路径引用
> feat: disableHostCheck and root import

- packages/atag/config/rollup.config.dev.js
- packages/atag/config/serve.js
- packages/atag/demo/index.html
- packages/atag/package.json
- packages/atag/src/components/camera/__tests__/camera.html
- packages/atag/src/components/camera/index.js
- packages/atag/src/index.js
- packages/atag/src/shared/compositeRenderAdatper.js
- packages/atag/src/shared/device.js
- packages/atag/tests/template.html
同层渲染适配器 beta + camera 组件适配
后面 adapter.js 独立拆分跟客户端发版走, 由客户端注册. (plan 下个月)
> feat: composite render adapter

- packages/driver-dom/src/index.js
> fix: Performance improve when node has been existed before nextSibling

- packages/rax-scripts/package.json
- packages/rax-scripts/src/config/babel.config.js
https://babeljs.io/docs/en/next/babel-plugin-transform-computed-properties.html
> feat: support transform-computed-properties“

- packages/atag/src/components/textarea/__tests__/textarea.js
- packages/atag/src/components/textarea/index.js
> fix: textarea show count

- packages/atag/src/components/animation/Pan.js
> fix: 修复 pan 类型在点击时候产生偏移值的 bug

- packages/atag/src/components/image/__tests__/image.html
- packages/atag/src/components/image/__tests__/image.js
- packages/atag/src/components/image/index.js
> fix: init image twice

- packages/atag/src/components/text/index.js
> refactor: text performance improve

- packages/mp-runtime/src/createPage.js
主要是为了修复原先 mergeState 的导致的时序问题。根据是否存在 updater 判断是否可以调用 setState 不太严谨, 改成按照组件所处的生命周期状态来调用
> fix: setData should not rely on internal variable 'updater' in rax

- packages/rax-miniapp-renderer/package.json
- packages/rax-miniapp-renderer/src/EventHandler.js
> Fix rax miniapp renderer

- packages/rax/src/__tests__/hooks.js
- packages/rax/src/hooks.js
同步更新useReducer api
相关pr [pr](https://github.com/facebook/react/pull/14723/files) [pr2](https://github.com/facebook/react/pull/14569)
> feat: update useReducer api

- packages/driver-worker/src/worker/Node.js
- packages/mp-runtime/package.json
- packages/mp-runtime/src/__tests__/__snapshots__/component.js.snap
- packages/mp-runtime/src/__tests__/component.js
- packages/mp-runtime/src/createComponent.js
> fix: duplicate style render

- packages/atag/src/components/map/map.native.js
In order to support the overseas map of fliggy，add parameter "abroad"
> feat: map component support abroad param

- packages/atag/package.json
- packages/atag/src/components/input/index.js
> fix: atag input value in iOS

- README.md
- packages/rax/package.json
- packages/rax/src/compat/index.js
- packages/rax/src/index.js
- scripts/dist-core.js
> feat: export react compatibility entry

- packages/miniapp-framework-web/src/container/__tests__/resolvePathname.js
- packages/miniapp-framework-web/src/container/index.js
- packages/miniapp-framework-web/src/container/resolve-pathname.js
> feat: load asset path relative to page path in web framework

- packages/rax-miniapp-renderer/src/NodeMap.js
> fix: recycle node reference of deleted node's childNodes

- packages/miniapp-framework-web/src/container/index.js
添加插件加载逻辑, normalizeURL 逻辑需要合并同步 https://github.com/alibaba/rax/pull/982 的改动
> feat: support load plugin in miniapp-framework-web

- packages/rax/src/index.js
> feat: add forwardRef

- packages/atag/src/components/map/map.native.js
- packages/atag/src/shared/compositeRenderAdatper.js
> Fix remove debounce native params

- packages/atag/src/components/input/index.js
> fix: remove inputType judgement

- packages/miniapp-framework-web/package.json
- packages/miniapp-framework-web/src/renderer/renderDOM.js
支持自定义 VIEWPORT_WIDTH
迁移的时候没有实现这个逻辑, 原先已经实现的
> feat: add support of VIEWPORT_WIDTH

- packages/atag/src/components/scroll-view/index.js
> fix: scroll-into-view

- packages/rax/src/vdom/native.js
> fix: style 'top: 0' can't update

- packages/jsx2mp/codegen/index.js
- packages/jsx2mp/parser/index.js
- packages/jsx2mp/parser/parseElement.js
- packages/jsx2mp/transformer/__tests__/base.test.js
- packages/jsx2mp/transformer/__tests__/condition.test.js
- packages/jsx2mp/transformer/__tests__/stripIndent.js
- packages/jsx2mp/transformer/transformJSX.js
> chore: support transfrom base structure

- packages/miniapp-webpack-plugin/package.json
- packages/miniapp-webpack-plugin/src/plugins/WebpackExternalApiPlugin.js
> Fix miniapp plugin

- packages/atag/src/components/swiper/index.js
- packages/atag/tests/template.html
> chore: fix swiper touch-action

- README.md
> docs: update features

- packages/atag/package.json
- packages/atag/src/shared/compositeRenderAdatper.js
> feat: add downgrade event for atag

- scripts/bench/frameworks/vue/package.json
https://travis-ci.org/alibaba/rax/builds/518607636
> fix: vue denpendencies config

- packages/mp-runtime/src/createPage.js
> ![image](https://user-images.githubusercontent.com/3922719/56025729-4992e100-5d45-11e9-9df7-744846d44543.png)
> fix: hack to avoid bug in windmill iOS 10

- README.md
> docs: fix grammar issue

- packages/miniapp-framework-web/config/webpack.config.dev.js
- packages/miniapp-framework-web/package.json
- packages/miniapp-framework-web/src/container/Router.js
- packages/miniapp-framework-web/src/container/env.js
- packages/miniapp-framework-web/src/container/index.js
- packages/miniapp-framework-web/src/container/my.js
- packages/miniapp-framework-web/src/worker/Client.js
- packages/miniapp-framework-web/src/worker/index.js
- packages/miniapp-framework-web/src/worker/my.js
1. 修复 query 丢失的问题
2. 新增 getSystemInfo 功能
3. 修复 rpx 失效的问题 (deviceWidth 未设置, 导致 setRem 的时候得到NaN)
> fix&feat: miniapp framework web

- packages/rax/index.d.ts
- packages/rax/src/index.d.ts
makes ts works properly.
after:
> chore: adjust d.ts export position

- packages/miniapp-webpack-plugin/package.json
- packages/miniapp-webpack-plugin/src/loaders/ExternalAPILoader.js
> fix: path error in windows

- README.md
- packages/rax-use-router/README.md
- packages/rax-use-router/src/index.js
> fix readme useRouter "Code Splitting" part

- packages/jsx-compiler/src/index.js
- packages/jsx2mp/bin/jsx2mp-start.js
- packages/jsx2mp/index.js
- packages/jsx2mp/package.json
- packages/jsx2mp/transformer/App.js
- packages/jsx2mp/transformer/Component.js
- packages/jsx2mp/transformer/Page.js
- packages/jsx2mp/transformer/Transformer.js
- packages/jsx2mp/transformer/Watch.js
- packages/jsx2mp/transformer/Watcher.js
- packages/jsx2mp/utils/file.js
- packages/jsx2mp/utils/log.js
- packages/jsx2mp/utils/npm.js
- packages/jsx2mp/watcher/index.js
jsx2mp add watch
jsx2mp add page transform
jsx2mp add components transform
> feat: jsx2mp cli tool

- packages/mp-runtime/src/__tests__/__snapshots__/component.js.snap
- packages/mp-runtime/src/__tests__/component.js
- packages/mp-runtime/src/createComponent.js
> fix: weixin mp props

- packages/jsx-compiler/src/modules/condition.js
- packages/jsx2mp/transformer/Watch.js
> fix: jsx2mp watch delete node_modules

- packages/miniapp-builder/package.json
- packages/miniapp-builder/src/builder/index.js
> fix: config glup version

- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/parser/__tests__/importedAndExported.js
- packages/jsx-compiler/src/parser/index.js
> fix: get exported and imoported with tests

- packages/jsx2mp/bin/jsx2mp-build.js
- packages/jsx2mp/bin/jsx2mp-start.js
- packages/jsx2mp/index.js
- packages/jsx2mp/transformer/App.js
- packages/jsx2mp/transformer/Transformer.js
- packages/jsx2mp/transformer/Watch.js
- packages/jsx2mp/utils/npm.js
Add component build feature for jsx2mp cli tool
> feat: add build component for jsx2mp

- packages/rax-scripts/package.json
- packages/rax-scripts/src/config/component/babel.config.js
> Fix duplicate babel plugin

- packages/rax-scripts/src/config/weexapp/webpack.config.base.js
fix the issue Error: Duplicate plugin/preset detected. when start weexapp:
> fix: 'Error: Duplicate plugin/preset detected.' when start weexapp

- packages/rax-scripts/package.json
- packages/rax-scripts/src/config/weexapp/webpack.config.base.js
> Fix weexapp babel config

- packages/driver-universal/src/dom.js
- packages/style-unit/src/index.js
style={{ width: "500" }} -> style={{ width: 500 }}
> feat: transform string to number

- packages/rax-server-renderer/package.json
- packages/rax-server-renderer/src/__tests__/renderToString.js
- packages/rax-server-renderer/src/index.js
- packages/rax/package.json
- packages/rax/src/createContext.js
fix context.Provider  context.Consumer in ssr
> fix: context in ssr

- packages/create-rax/README.md
- packages/create-rax/bin/create.js
- packages/create-rax/package.json
> Feat create rax

- packages/rax-cli/package.json
- packages/rax-cli/src/generator/component/package.json
fix: https://github.com/alibaba/rax/issues/1118
> fix: component start error  in windows

- CNAME
Discuss about applying a cname to rax.js.org
> chore: add CNAME for rax.js.org

- packages/rax-dom/package.json
- packages/rax/package.json
> rax v1.0.7

- packages/rax-scripts/package.json
- packages/rax-scripts/src/config/webpack.config.js
app.json 增加 publicPath 配置。
app.json add publicPath config to update webpack publicPath
> feat: app.json add publicPath config to update webpack publicPath

- packages/rax-webpack-plugin/package.json
- packages/rax-webpack-plugin/src/PlatformLoader.js
fix warning of loader-utils
https://github.com/webpack/loader-utils/issues/56
> fix: loader-utils-warning

- packages/mp-loader/package.json
- packages/mp-loader/src/__tests__/__snapshots__/template-loader.js.snap
- packages/mp-loader/src/template-loader.js
修复 __data__ 下变量在 web-view 场景下未注入的问题
> Fix miniapp

- docs/en-US/driver-spec.md
> fix(docs): typo fix in docs

- packages/jsx-compiler/src/modules/components.js
> fix: tag name does not support special characters

- packages/rax-server-renderer/src/__tests__/renderToString.js
- packages/rax-server-renderer/src/index.js
> Feat support style list in ssr

- CNAME
- index.html
> feat: add rax.js.org

- index.html
> fix: redirect widget button cursor

- packages/rax-cli/bin/rax.js
- packages/rax-cli/package.json
- packages/rax-cli/src/generator/index.js
- packages/rax-cli/src/generator/template-processer.js
- 工程合一后新的初始化流程，取消 UniversalApp webapp 增加 app 和 api ，增加选择 build target。
- 工程模版使用 ejs 语法，方便初始化时向模版注入代码能力。
> Feat new initialization workflow

- packages/rax-is-valid-element/src/index.js
> fix: The fix isValidElement method returns a Boolean value

- packages/rax-plugin-app/package.json
- packages/rax-plugin-app/src/config/defaultUserConfig.js
- packages/rax-plugin-app/src/config/getWebpackBase.js
- packages/rax-plugin-app/src/config/web/getBase.js
- packages/rax-plugin-app/src/config/web/setBuild.js
- packages/rax-plugin-app/src/config/web/setDev.js
- packages/rax-plugin-app/src/config/weex/getBase.js
- packages/rax-plugin-app/src/config/weex/setBuild.js
- packages/rax-plugin-app/src/config/weex/setDev.js
- packages/rax-plugin-app/src/index.js
- packages/rax-plugin-app/src/plugins/UniversalDocumentPlugin.js
- packages/rax-scripts/package.json
> fix: fix publicPath

- packages/rax-cli/src/generator/api/build.json
- packages/rax-plugin-api/package.json
- packages/rax-plugin-api/src/build.js
- packages/rax-plugin-api/src/defaultUserConfig.js
- packages/rax-plugin-api/src/dev.js
- packages/rax-plugin-api/src/filePattern.js
- packages/rax-plugin-api/src/index.js
- packages/rax-plugin-api/src/registerTask.js
- packages/rax-plugin-component/package.json
- packages/rax-plugin-component/src/build.js
- packages/rax-plugin-component/src/config/defaultUserConfig.js
- packages/rax-plugin-component/src/config/getDevConfig.js
- packages/rax-plugin-component/src/index.js
- packages/rax-scripts/package.json
fix com&api plugin default config
> fix: fix-com&api-config

- packages/rax-cli/src/generator/app/_package.json
- packages/universal-app-shell-loader/package.json
- packages/universal-app-shell-loader/src/index.js
> Feat: add SSR client router initialComponent

- packages/rax-scripts/package.json
- packages/rax-scripts/src/config/component/webpack.config.dev.js
- packages/rax-scripts/src/config/universalapp/webpack.config.base.js
- packages/rax-scripts/src/config/webapp/webpack.config.base.js
- packages/rax-scripts/src/config/webpack.config.js
> fix: fix weex external

- packages/rax-plugin-app/package.json
- packages/rax-plugin-app/src/config/web/getBase.js
- packages/rax-plugin-app/src/index.js
- packages/rax-plugin-app/src/plugins/UniversalDocumentPlugin.js
fix document publicPath config
> fix: fix document plugin public

- packages/universal-app-shell-loader/package.json
- packages/universal-app-shell-loader/src/index.js
> Fix: remove web-app index.html font-size

- packages/driver-dom/package.json
- packages/driver-dom/src/index.js
1. support rpx in style
~~2. support array style~~
3. support setUnitPrecision
> feat: support rpx for driver-dom

- packages/rax-plugin-app/package.json
- packages/rax-plugin-app/src/dev.js
> feat: add qrcode

- packages/rax-plugin-app/package.json
- packages/rax-plugin-app/src/config/miniapp/getOutputPath.js
change dir from build-miniapp to build/miniapp
> fix: change mp build dir

- packages/jsx2mp-runtime/src/bridge.js
- packages/jsx2mp-runtime/src/component.js
- packages/jsx2mp-runtime/src/cycles.js
> fix: jsx2mp page cycles

- packages/rax-plugin-app/package.json
- packages/rax-plugin-app/src/config/babel.config.js
- packages/rax-plugin-app/src/config/web/getBase.js
- packages/rax-plugin-app/src/config/web/setDev.js
- packages/rax-plugin-app/src/config/weex/getBase.js
- packages/rax-plugin-app/src/config/weex/setDev.js
> Fix inline style

- packages/driver-dom/src/index.js
> fix: driver-dom isRpx judge string

- packages/jsx-compiler/src/modules/components.js
> fix: cell default style

- packages/rax-plugin-app/src/config/web/setDev.js
- packages/rax-plugin-app/src/config/weex/setDev.js
- packages/rax-plugin-app/src/plugins/UniversalDocumentPlugin.js
> feat: devPublic

- packages/rax-plugin-app/src/build.js
- packages/rax-plugin-app/src/config/web/setBuild.js
- packages/rax-plugin-app/src/config/web/setDev.js
- packages/rax-plugin-app/src/config/weex/setBuild.js
- packages/rax-plugin-app/src/config/weex/setDev.js
- packages/rax-plugin-app/src/plugins/UniversalDocumentPlugin.js
- packages/style-unit/package.json
- packages/universal-app-runtime/package.json
- packages/universal-app-shell-loader/package.json
- packages/universal-app-shell-loader/src/index.js
> Feat fix minimize

- packages/jsx-compiler/README.md
- packages/jsx-compiler/src/modules/code.js
- packages/jsx-compiler/src/modules/components.js
- packages/jsx-compiler/src/modules/css.js
- packages/jsx-compiler/src/modules/template.js
- packages/jsx2mp-loader/src/app-loader.js
- packages/jsx2mp-loader/src/component-loader.js
- packages/jsx2mp-loader/src/page-loader.js
- 整理传入 jsx-compiler 的 path 参数
- 修复引用 css styles file 时 output path 错误的 bug
> refactor: neaten passed path in jsx-compiler

- packages/rax/src/vdom/native.js
> fix: check child

- packages/jsx-compiler/src/modules/__tests__/condition.js
- packages/jsx-compiler/src/modules/__tests__/list.js
- packages/jsx-compiler/src/modules/condition.js
> fix: conditional identifier test case

- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/modules/__tests__/condition.js
- packages/jsx-compiler/src/modules/__tests__/element.js
- packages/jsx-compiler/src/modules/__tests__/list.js
- packages/jsx-compiler/src/modules/condition.js
- packages/jsx-compiler/src/modules/element.js
1. fix conditional identifier case #1250 
2. fix: collect dynamic identifier instead of object prop (#1252)
> [RELEASE] JSX2MP 0815

- packages/driver-dom/src/index.d.ts
- packages/driver-universal/src/index.d.ts
- packages/driver-weex/src/index.d.ts
- packages/rax/index.d.ts
- packages/rax/src/index.d.ts
1. fix #1244 
2. add ts declearation files for drivers
3. remove Rax namespace declearation
> Fix ts declear

- packages/driver-universal/package.json
- packages/driver-universal/src/dom.js
> fix: driver universal style array

- packages/jsx2mp-loader/package.json
- packages/jsx2mp-loader/src/file-loader.js
> Fix tnpm folder files

- packages/jsx2mp-cli/bin/jsx2mp-build.js
- packages/jsx2mp-cli/bin/jsx2mp-start.js
- packages/jsx2mp-cli/default.js
- packages/jsx2mp-cli/getWebpackConfig.js
- packages/jsx2mp-cli/index.js
- packages/jsx2mp-cli/package.json
修复 rax-scripts 适配, refactor code
> refactor: set default value for jsx2mp-cli

- packages/jsx2mp-cli/package.json
- packages/jsx2mp-cli/utils/file.js
- packages/jsx2mp-cli/utils/npm.js
> Chore replace colors with chalk

- packages/jsx2mp-loader/src/file-loader.js
> fix: npm dep file relative path

- packages/rax-plugin-app/package.json
- packages/rax-plugin-app/src/config/user/keys/inlineStyle.js
- packages/rax-plugin-component/package.json
- packages/rax-plugin-component/src/config/user/default.config.js
- packages/rax-plugin-component/src/config/user/keys/inlineStyle.js
> feat: add rpx2vw

- packages/jsx-compiler/src/modules/code.js
- packages/jsx2mp-cli/getWebpackConfig.js
- packages/jsx2mp-cli/package.json
- packages/jsx2mp-loader/package.json
- packages/jsx2mp-loader/src/babel-plugin-rename-import.js
- packages/jsx2mp-loader/src/file-loader.js
1. Fix support scoped packages
2. Fix scoped packages and installed with tnpm symbolic folders
> fix: support scoped packages

- packages/rax-get-element-by-id/README.md
- packages/rax-get-element-by-id/package.json
- packages/rax-get-element-by-id/src/index.js
- packages/rax-set-native-props/README.md
- packages/rax-set-native-props/package.json
- packages/rax-set-native-props/src/flexbox.js
- packages/rax-set-native-props/src/index.js
> Add rax-set-native-props & rax-get-element-by-id

- packages/rax-plugin-app/package.json
- packages/rax-plugin-app/src/config/user/default.config.js
- packages/rax-plugin-app/src/config/user/keys/hash.js
- packages/rax-plugin-app/src/config/user/keys/inlineStyle.js
- packages/rax-plugin-app/src/config/web/setDev.js
- packages/rax-plugin-app/src/plugins/UniversalDocumentPlugin.js
- packages/rax-plugin-multi-pages/package.json
- packages/rax-plugin-multi-pages/src/index.js
- packages/rax-plugin-ssr/package.json
- packages/rax-plugin-ssr/src/ssr/setDev.js
> [Feat] plugin app add hash config

- packages/jsx2mp-cli/bin/jsx2mp-build.js
- packages/jsx2mp-cli/bin/jsx2mp-start.js
- packages/jsx2mp-cli/index.js
- packages/jsx2mp-cli/utils/spinner.js
> feat: support skipClearStdout

- 404.html
- index.html
> fix: default data

- 404.html
- index.html
> Feat update 0 4 17

- packages/rax/src/hooks.js
- packages/rax/src/vdom/fragment.js
- packages/rax/src/vdom/reactive.js
> Refactor compress variables

- packages/rax/src/vdom/reactive.js
Decrease `17B` in raw (uglified js file).
> refactor: try to decrease code size

- packages/rax/src/vdom/composite.js
- packages/rax/src/vdom/fragment.js
> Revert "fix: optimize performance and reduce package size"

- packages/rax/src/vdom/instantiateComponent.js
> feat: little opt

- packages/rax/src/vdom/component.js
- packages/rax/src/vdom/composite.js
> refactor: compress isPureComponent

- packages/driver-universal/package.json
- support setProperty for css vars
> chore: bump driver-universal of 1.0.3-0

- packages/rax/src/__tests__/fragment.js
> fix: fragment test case

- packages/mobx-rax/package.json
- packages/mobx-rax/src/Provider.js
- packages/mobx-rax/src/observer.js
> feat: mobx-rax support rax1.x

- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/modules/code.js
> fix: jsx-compiler ignore universal-app-runtime

- 404.html
- index.html
> update rax.js.org version 0.4.20

- packages/rax/src/vdom/native.js
> chore: reduce code size

- packages/rax/src/vdom/__tests__/composite.js
- packages/rax/src/vdom/composite.js
- packages/rax/src/vdom/fragment.js
- packages/rax/src/vdom/native.js
Current componentDidMount called after appendChild, but the parent is not appendChild to root.
> fix: componentDidMount exec not correct

- packages/driver-worker/package.json
- packages/driver-worker/src/Driver.js
Upgrade style-unit support to driver-worker.
> feat: adopt to style-unit 2.0

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/question.md
You are using an old version of issue templates. Please update to the new issue template workflow. [Learn more](https://help.github.com/articles/about-issue-and-pull-request-templates)
> Update to modern issue templates

- packages/rax/src/vdom/reactive.js
> chore: remove useless function

- packages/jsx-compiler/src/modules/__tests__/components.js
- packages/jsx-compiler/src/modules/components.js
- packages/jsx-compiler/src/parser/index.js
1. traverse ast 的过程中只搜集 rename 后自定义组件名及引入路径的对应关系，transfrom 之后再生成 usingComponents
2. 添加自定义组件单测
> chore: add custom component test

- packages/jsx2mp-cli/bin/jsx2mp-build.js
- packages/jsx2mp-cli/bin/jsx2mp-start.js
- packages/jsx2mp-cli/default.js
- packages/jsx2mp-cli/getWebpackConfig.js
- packages/jsx2mp-cli/index.js
- packages/jsx2mp-cli/utils/file.js
- packages/jsx2mp-loader/src/component-loader.js
- packages/jsx2mp-loader/src/page-loader.js
1. support copying multiple directories to dist path (for static files used in .json file and local miniapp components)
> feat: support copy constant dir

- packages/jsx-compiler/src/codegen/genCode.js
- packages/jsx-compiler/src/codegen/index.js
- packages/jsx2mp-cli/getWebpackConfig.js
- packages/jsx2mp-loader/package.json
- packages/jsx2mp-loader/src/app-loader.js
- packages/jsx2mp-loader/src/component-loader.js
- packages/jsx2mp-loader/src/page-loader.js
- packages/jsx2mp-loader/src/script-loader.js
- packages/jsx2mp-loader/src/utils/addSourceMap.js
- support generating source maps in build mode with both wechat and alipay IDE tested
> feat: generating source maps

- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/modules/components.js
- packages/jsx2mp-loader/src/babel-plugin-rename-import.js
1. fix path resolve error in usingComponets
2. fix path resolve error in single script files when importing npm dependency
> Fix copy path

- packages/jsx-compiler/src/modules/code.js
- packages/jsx-compiler/src/modules/condition.js
- packages/jsx2mp-runtime/src/bridge.js
- packages/jsx2mp-runtime/src/component.js
- packages/jsx2mp-runtime/src/enqueueRender.js
- packages/jsx2mp-runtime/src/updater.js
1. Remove useless code
2. After get component instance, check whether has render callback
> fix: jsx2mp runtime

- packages/jsx-compiler/src/modules/__tests__/condition.js
- packages/jsx-compiler/src/modules/condition.js
> feat: support logical expression with jsx

- packages/jsx-compiler/src/modules/__tests__/attribute.js
- packages/jsx-compiler/src/modules/__tests__/element.js
- packages/jsx-compiler/src/modules/attribute.js
- packages/jsx-compiler/src/modules/code.js
- packages/jsx-compiler/src/modules/element.js
- packages/jsx-compiler/src/modules/index.js
- packages/jsx2mp-runtime/src/component.js
- packages/jsx2mp-runtime/src/hooks.js
1. Support useRef in jsx2mp
2. Support ref is string
> feat: support useRef

- packages/jsx2mp-cli/getWebpackConfig.js
- packages/jsx2mp-loader/src/app-loader.js
```json
{
"routes": [
{
"path": "/",
"source": "pages/Home/index",
"targets": ["web"]
}
]
}
```
配置如上时，小程序端不构建该页面
> feat: support build differentiated platform

- packages/jsx-compiler/src/modules/code.js
- packages/jsx-compiler/src/modules/components.js
- packages/jsx2mp-cli/__tests__/component.js
- packages/jsx2mp-cli/bin/jsx2mp-build.js
- packages/jsx2mp-cli/bin/jsx2mp-start.js
- packages/jsx2mp-cli/getWebpackConfig.js
- packages/jsx2mp-cli/index.js
- packages/jsx2mp-loader/src/app-loader.js
- packages/jsx2mp-loader/src/babel-plugin-rename-import.js
- packages/jsx2mp-loader/src/component-loader.js
- packages/jsx2mp-loader/src/output.js
- packages/jsx2mp-loader/src/page-loader.js
- packages/jsx2mp-loader/src/script-loader.js
1. support disable-copy-npm mode
2. compile code to es5 in build mode
> feat: disable copy npm

- packages/jsx-compiler/src/modules/__tests__/function.js
- packages/jsx-compiler/src/modules/function.js
- packages/jsx-compiler/src/modules/index.js
小程序代码中含有 `require('weex-module/xxx')` 会报错
> chore: remove require weex module

- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/adapter.js
- packages/jsx-compiler/src/baseComponents.js
- packages/jsx-compiler/src/compiledComponents.js
- packages/jsx-compiler/src/modules/__tests__/attribute.js
- packages/jsx-compiler/src/modules/__tests__/components.js
- packages/jsx-compiler/src/modules/__tests__/function.js
- packages/jsx-compiler/src/modules/__tests__/list.js
- packages/jsx-compiler/src/modules/attribute.js
- packages/jsx-compiler/src/modules/components.js
- packages/jsx-compiler/src/modules/element.js
- packages/jsx-compiler/src/modules/function.js
- packages/jsx-compiler/src/modules/index.js
- packages/jsx-compiler/src/modules/list.js
- packages/jsx2mp-cli/__tests__/component.js
- packages/jsx2mp-cli/package.json
- packages/jsx2mp-loader/package.json
- packages/jsx2mp-loader/src/babel-plugin-rename-import.js
- packages/jsx2mp-loader/src/component-loader.js
- packages/jsx2mp-runtime/package.json
- packages/jsx2mp-runtime/src/bridge.js
- packages/jsx2mp-runtime/src/component.js
TODO:
1. [Feat] Support createRef
2. [Feat] 循环渲染中事件绑定传参使用临时变量 @SoloJiang
3. [Feat] 微信小程序样式 @SoloJiang
...
More wait @ChrisCindy
> JSX2MP @ 1031

- packages/jsx2mp-cli/getWebpackConfig.js
> fix: use main property in package.json when webpack resolves file path

- packages/jsx2mp-loader/src/babel-plugin-rename-import.js
- packages/jsx2mp-loader/src/script-loader.js
- 微信小程序无法自动检索省略 index 的路径，因此为所有路径补齐 index
> feat(miniapp): add index in path if it's omitted

- packages/jsx-compiler/src/modules/css.js
- packages/jsx2mp-cli/getWebpackConfig.js
- packages/jsx2mp-loader/package.json
- packages/jsx2mp-loader/src/app-loader.js
- packages/jsx2mp-loader/src/component-loader.js
- packages/jsx2mp-loader/src/page-loader.js
- packages/jsx2mp-loader/src/styleProcessor.js
- support css preprocessors including sass/less/stylus
> feat(miniapp): support css preprocessors

- packages/jsx2mp-loader/src/script-loader.js
- fix: can't modify corresponding usingComponents json file when building in other platforms like wechat
> fix(miniapp): can't modify corresponding usingComponents file path

- packages/jsx-compiler/src/modules/__tests__/jsx-plus.js
- packages/jsx-compiler/src/modules/code.js
- packages/jsx-compiler/src/modules/jsx-plus.js
- packages/jsx2mp-runtime/src/classnames.js
- packages/jsx2mp-runtime/src/index.js
> feat: jsx plus x-class support

- packages/jsx-compiler/src/modules/__tests__/attribute.js
- packages/jsx-compiler/src/modules/attribute.js
- packages/jsx-compiler/src/modules/element.js
- packages/jsx2mp-runtime/src/adapter/ali.js
- packages/jsx2mp-runtime/src/adapter/wechat.js
- packages/jsx2mp-runtime/src/bridge.js
1. 支持在微信小程序自定义组件上设置样式
2. runtime 多平台小程序的基础差异配置放进 adapter
> feat: support set style on wechat custom component

- packages/jsx2mp-cli/getWebpackConfig.js
- packages/jsx2mp-loader/package.json
- packages/jsx2mp-loader/src/app-loader.js
- packages/jsx2mp-loader/src/component-loader.js
- packages/jsx2mp-loader/src/page-loader.js
- Catch error when compiling app/page/component
- Optimize error report
> feat: optimize error report

- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/modules/components.js
- packages/jsx2mp-cli/package.json
- packages/jsx2mp-loader/package.json
- packages/jsx2mp-runtime/package.json
npm components aren't taged __parentId
> fix: npm component parentId

- 404.html
- index.html
> feat: v0.4.23

- packages/jsx-compiler/src/modules/__tests__/attribute.js
- packages/jsx-compiler/src/modules/attribute.js
- packages/jsx-compiler/src/modules/element.js
- packages/jsx2mp-runtime/src/component.js
- packages/jsx2mp-runtime/src/updater.js
1. Fix will receive props
2. Fix style & class insert rule
> fix: will receive props

- packages/jsx-compiler/src/modules/element.js
- packages/jsx2mp-cli/__tests__/component.js
- packages/jsx2mp-cli/demo/component.js
`<Row a={b && c} e={f ? g : h} />`
应该编译成
```js
this.updateChildProps({
a: b && c,
e: f ? g : h
});
```
实际编译成：
```js
this.updateChildProps({
a: _d0 && _d1,
e: _d2 ? _d3 : _d4
});
```
> fix: component attr complex expression compile

- packages/jsx-compiler/src/adapter.js
- packages/jsx-compiler/src/modules/__tests__/jsx-plus.js
- packages/jsx-compiler/src/modules/element.js
- packages/jsx-compiler/src/modules/jsx-plus.js
- packages/jsx2mp-cli/getWebpackConfig.js
> feat: support x-slot

- packages/jsx2mp-runtime/src/component.js
- packages/jsx2mp-runtime/src/hooks.js
Hooks rerender need be scheduled.
> chore: optimize hooks render

- packages/jsx-compiler/src/modules/code.js
Fix jsx2mp hooks import method
> fix: hooks has already been declared

- packages/jsx2mp-runtime/src/bridge.js
- The second param in runApp will be injected to page props
> feat(miniapp): add pageConfig from runApp

- packages/jsx-compiler/src/modules/attribute.js
- packages/jsx-compiler/src/modules/element.js
> fix: loop temp variable

- packages/jsx2mp-runtime/src/bridge.js
Fix event proxy get dataset target
> fix: event target

- packages/rax-set-native-props/package.json
> fix(dep): rax should be peer dep of rax-set-native-props

- packages/stylesheet-loader/package.json
- packages/stylesheet-loader/src/index.js
> fix: update deperated loader utils

- packages/rax-server-renderer/src/__tests__/form.js
- packages/rax-server-renderer/src/__tests__/fragment.js
- packages/rax-server-renderer/src/__tests__/lifecycle.js
- packages/rax-server-renderer/src/__tests__/memo.js
- packages/rax-server-renderer/src/__tests__/refs.js
- packages/rax-server-renderer/src/__tests__/url.js
- packages/rax-server-renderer/src/index.js
tests for : form, lifecycle, url, memo, fragment
fix render for defaultValue
> Tests for ssr

- packages/rax-app/package.json
Just update rax-app package.json version
> feat: update rax-app version

- packages/jsx-compiler/src/modules/code.js
- packages/jsx-compiler/src/modules/function.js
- packages/jsx-compiler/src/parser/index.js
- packages/jsx-compiler/src/utils/checkModule.js
- packages/jsx-compiler/src/utils/getProgramPath.js
- packages/jsx2mp-cli/__tests__/component.js
1. Support wrap handle function around component, like `export default forwardRef(Button)`
2. Support add props to component, like `Button.propsType = {}`
3. Support `useLayoutEffect`
> feat: support wrap handle function around component 

- packages/rax/src/validateChildKeys.js
> fix: compatible with console in some platform that now support %s

- packages/driver-universal/package.json
- packages/driver-universal/src/__tests__/dom-rpx-transformer.js
- packages/driver-universal/src/dom.js
- packages/driver-universal/src/index.js
- packages/driver-universal/src/kraken.js
- packages/driver-universal/src/weex.js
Add a new platform support: kraken
> feat: add kraken driver for universal driver

- packages/jsx-compiler/src/modules/__tests__/condition.js
- packages/jsx-compiler/src/modules/condition.js
> fix(jsx2mp): IfStatement compiler

- packages/driver-dom/package.json
- packages/driver-universal/package.json
- packages/rax-app/package.json
- packages/rax-app/src/runApp.js
> chore: bump versions

- packages/postcss-plugin-rpx2vw/src/__tests__/index.js
- packages/stylesheet-loader/package.json
- packages/stylesheet-loader/src/__tests__/particular.js
- packages/stylesheet-loader/src/particular.js
fix [ref](https://github.com/alibaba/rax/issues/1575)
> fix: convert without unit

- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/modules/__tests__/jsx-plus.js
- packages/jsx-compiler/src/modules/jsx-plus.js
> fix(jsx2mp): nested loop

- packages/jsx-compiler/src/modules/element.js
- packages/jsx2mp-runtime/src/component.js
- packages/jsx2mp-runtime/src/history.js
- packages/jsx2mp-runtime/src/updater.js
1. Fix: UnaryExpression in loop, like `<View x-for={item in list}><Text x-if={!item.show}>xxx</Text></View>`
2. Perf: make component first render different from update render, especially when there are many components
3. Fix:  `shouldComponentUpdate` & `componentWillReceiveProps` called time
> chore(jsx2mp): fix UnaryExpression compile & improve runtime performance

- packages/jsx2mp-loader/src/script-loader.js
fix: https://github.com/alibaba/rax/issues/1591
> fix: use path.sep in path resolve to support windows

- packages/jsx2mp-runtime/src/component.js
1. Support setState callback
2. Fix did mount cycle is called time
> fix(jsx2mp): change triggered time of did mount cycle

- packages/jsx-compiler/src/modules/code.js
- packages/jsx-compiler/src/modules/components.js
- packages/jsx-compiler/src/utils/pathHelper.js
- packages/jsx2mp-loader/src/script-loader.js
- packages/jsx2mp-loader/src/utils/isMiniappComponent.js
1. support using specific npm files like `import add from 'lodash/fp/add'`
2. support using third miniapp component like `import Card from 'mini-antui/es/card/index'`
> feat(miniapp): npm specific path process

- packages/jsx2mp-runtime/src/updater.js
> fix(jsx2mp): child should be updated after parent set data

- packages/babel-plugin-transform-jsx-stylesheet/package.json
- packages/babel-plugin-transform-jsx-stylesheet/src/__tests__/index.js
- packages/babel-plugin-transform-jsx-stylesheet/src/index.js
1. 不转换 `import styles from './app.css';` 里的 styles 变量
2. 补充边缘 case
> fix: style transform

- packages/jsx-compiler/src/modules/__tests__/element.js
- packages/jsx-compiler/src/modules/element.js
`<View onClick={(event) => goUrl(data.link)}>{data.text}</View>`
=>
`<block a:if="{{$ready}}"><view onTap="_e0" data-e0-arg-0="{{_d0.link}}" class="__rax-view">{{ _d0.text }}</view></block>`
> fix(jsx2mp): event bind

- packages/jsx2mp-runtime/src/router.js
Support use withRouter :
```jsx
import { withRouter } from 'rax-app';
function Todo({ history }) {
console.log(history);
}
export default withRouter(Todo);
```
> feat(jsx2mp): support withRouter

- packages/jsx-compiler/src/modules/components.js
```js
this._updateChildProps("7" + "-" + "index" + "-" + idx, {
"text": it
});
```
=>
```js
this._updateChildProps("7" + "-" + index + "-" + idx, {
"text": it
});
```
> fix(jsx2mp): nested loop compile

- packages/driver-dom/README.md
- packages/driver-miniapp/README.md
- packages/driver-miniapp/package.json
- packages/driver-miniapp/src/index.d.ts
- packages/driver-miniapp/src/index.js
- 增加 driver-miniapp 包，用于小程序运行时方案下使用
> feat(miniapp): add driver-miniapp package

- packages/rax-pwa/package.json
- packages/rax-pwa/src/Navigation/index.js
- packages/rax-pwa/src/TabBar/index.js
- packages/rax-pwa/src/__tests__/Navigation.js
- packages/rax-pwa/src/__tests__/TabBar.js
Use path to locate TabBar page,  as same as miniApp.
```json
{
"tabBar": {
"textColor": "#999999",
"selectedColor": "#666",
"backgroundColor": "#f8f8f8",
"items": [
{
"name": "welcome",
"path": "/",
"icon": "https://gw.alicdn.com/tfs/TB1ypSMTcfpK1RjSZFOXXa6nFXa-144-144.png",
"activeIcon": "https://gw.alicdn.com/tfs/TB1NBiCTgHqK1RjSZFPXXcwapXa-144-144.png"
}
]
}
}
```
> Feat add TabBar config `path`

- packages/rax-app/package.json
- packages/rax-pwa/package.json
Support `path` to appoint TabBar items
```json
{
"routes": [                    
{
"path": "/",
"source": "pages/Home"
}
],
"tabBar": {
"textColor": "#999",
"selectedColor": "#666",
"backgroundColor": "#f8f8f8",
"items": [
{
"name": "home",
"path": "/",
"icon": "https://gw.alicdn.com/tfs/TB1ypSMTcfpK1RjSZFOXXa6nFXa-144-144.png",
"activeIcon": "https://gw.alicdn.com/tfs/TB1NBiCTgHqK1RjSZFPXXcwapXa-144-144.png"
}
]
}
}
```
> Feat upgrade rax-pwa TabBar setting

- packages/rax-use-import/package.json
- packages/rax-use-import/src/index.js
> Feat use import args

- packages/jsx-compiler/src/modules/components.js
Fix mutiple nested loop render
> fix: mutiple nested loop

- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/modules/__tests__/components.js
- packages/jsx-compiler/src/modules/components.js
- packages/jsx2mp-cli/__tests__/component.js
- packages/jsx2mp-runtime/src/bridge.js
> fix: multidimensional loop render problem

- README.md
- packages/rax/src/devtools/index.js
- packages/rax/src/devtools/reconciler.js
- packages/rax/src/index.js
Make user not need import `rax/lib/devtools` anymore.
> feat: devtools usage make more easy

- README.md
Feat readme add VS Code Extensions description
> Feat readme add VS Code Extensions description

- packages/rax-app/package.json
- packages/rax-app/src/runApp.js
AppConfig support set history.
```
import { runApp } from 'rax-app';
import appConfig from './app.json';
import { createBrowserHistory } from 'history';
appConfig.history = createBrowserHistory();
runApp(appConfig);
```
> Feat appConfig add history

- packages/rax/package.json
- packages/rax/src/vdom/__tests__/fragment.js
- packages/rax/src/vdom/native.js
> fix: rax remove child with all children in fragment

- packages/jsx2mp-runtime/package.json
- packages/jsx2mp-runtime/src/app.js
- packages/jsx2mp-runtime/src/bridge.js
- packages/jsx2mp-runtime/src/cycles.js
- packages/jsx2mp-runtime/src/index.js
- packages/jsx2mp-runtime/src/page.js
- packages/jsx2mp-runtime/src/pageInstanceMap.js
- add useAppShow/useAppHide/useAppError/useAppshare hooks
- add usePageShare hooks to replace useShareAppMessage which will be deprecated in next version
- refactor page lifecycles to inject hooks when needed
> feat(jsx2mp): refactor page lifecycles hooks && add app lifecycles hooks

- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/modules/__tests__/condition.js
- packages/jsx-compiler/src/modules/condition.js
```jsx
const MyComponent = (props = {}) => {
let content = "123" + a.x;
if (a.y > 0) {
content = 1111
} else if (a.z === 0) {
content = 232
}
return (
<Text>
{content}
</Text>
);
};
```
> refactor(jsx2mp): handle ifstatement

- packages/jsx-compiler/src/modules/__tests__/condition.js
- packages/jsx-compiler/src/modules/condition.js
> fix: assignment's right is a normal expression

- README.md
Add community support
- [GitHub](https://github.com/alibaba/rax) (Bug reports, contributions)
- [Twitter](https://twitter.com/RaxNews) (Get the news fast)
- [Medium](https://medium.com/@raxjs) (Get blogs and articles)
- [知乎专栏](https://zhuanlan.zhihu.com/raxjs) (Get blogs and articles in Simplified Chinese)
> docs: add community support

- packages/jsx2mp-runtime/src/adapter/ali.js
- packages/jsx2mp-runtime/src/adapter/wechat.js
- packages/jsx2mp-runtime/src/bridge.js
- packages/jsx2mp-runtime/src/history.js
- packages/jsx2mp-runtime/src/index.js
- packages/jsx2mp-runtime/src/nativeEventListener.js
- packages/jsx2mp-runtime/src/page.js
In page:
```jsx
import { createElement } from 'rax';
import { registerNativeEventListeners } from 'rax-app';
import Child from './Child';
function App() {
return <Child />
}
if (isMiniApp || isWechatMiniprogram) {
registerNativeEventListeners(App, ['onTitleClick']);
}
export default App;
```
In child:
```jsx
import { createElement, useEffect } from 'rax';
import { addNativeEventListener } from 'rax-app';
export default function Child() {
useEffect({
addNativeEventListener('onTiltleClick', () => {
console.log('Title is clicked~');
})
}, [])
return <view></view>
}
```
> feat(jsx2mp): support add native event listener

- packages/jsx-compiler/src/modules/__tests__/condition.js
- packages/jsx-compiler/src/modules/condition.js
```jsx
function Home() {
const app = getApp();
const [a, setState] = useState(1);
useEffect(() => {
const { isLogin } = app;
let a = 2;
if (isLogin) {
a = 1;
}
setState(a);
}, []);
return (
<View>{a}</View>
);
}
```
> fix(jsx2mp): local value and render value are the same in IfStatement

- packages/rax-server-renderer/package.json
- packages/rax-server-renderer/src/index.js
After about 30 reloads, the memory snapshot is like this：
before:
after:
> Fix: memory leak in ssr

- packages/rax-document/README.md
- packages/rax-document/package.json
- packages/rax-document/src/index.js
https://github.com/raxjs/rax-scripts/pull/186
> feat: pass page name to document

- packages/jsx2mp-cli/bin/jsx2mp.js
> fix(jsxmp2-cli): warn the user for passing in unknown commands

- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/modules/__tests__/jsx-plus.js
- packages/jsx-compiler/src/modules/__tests__/list.js
- packages/jsx-compiler/src/modules/code.js
- packages/jsx-compiler/src/modules/element.js
- packages/jsx-compiler/src/modules/index.js
- packages/jsx-compiler/src/modules/jsx-plus.js
- packages/jsx-compiler/src/modules/list.js
- packages/jsx-compiler/src/modules/style.js
- packages/jsx-compiler/src/utils/handleList.js
- packages/jsx-compiler/src/utils/handleListJSXExpressionContainer.js
-  Fix `x-class` in loop render
- Fix event params bind in loop render
- Support use format function in loop jsx, like `<View>{format(index)}</View>`
> fix(jsx2mp): special loop case

- packages/rax-app/package.json
- packages/rax-app/src/runApp.js
Remove promise(only used resolve) catch method in runApp.  
The onerror event will be triggered by runApp error.
> Feat remove runapp catch

- packages/rax-types/README.md
- packages/rax-types/package.json
- packages/rax-types/src/index.d.ts
> Feat rax types

- packages/rax-server-renderer/package.json
- packages/rax-server-renderer/src/__tests__/styles.js
- packages/rax-server-renderer/src/index.js
Fix server side render error when pass string value to numerical property. eg:  fontWeight: '600'
> fix: numerical property

- packages/rax-app/package.json
- packages/rax-app/src/runApp.js
Page component's props contains `history`, `routes` and `InitialComponent`.
withRouter component's props contains `history` and `location`.
Add location props to page component, works in  web, weex, miniApp
> Feat page props add location

- 404.html
- index.html
站点版本升级至 0.4.34
去掉导航的 pha 入口，文档侧边栏体验优化
> feat: v0.4.34

- packages/jsx-compiler/src/utils/getExportComponentPath.js
Support:
```jsx
const MyComponent = (props) => {
return <View>123</View>
};
function handleComponent(Com) {
return Com;
}
export default handleComponent(MyComponent);
```
> feat(jsx2mp): support variable declarator function

- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/adapter.js
- packages/jsx-compiler/src/modules/__tests__/attribute.js
- packages/jsx-compiler/src/modules/__tests__/components.js
- packages/jsx-compiler/src/modules/attribute.js
- packages/jsx-compiler/src/modules/code.js
- packages/jsx-compiler/src/modules/components.js
- packages/jsx-compiler/src/modules/element.js
- packages/jsx-compiler/src/utils/generateId.js
- packages/jsx2mp-runtime/src/adapter/getComponentBaseConfig.js
- packages/jsx2mp-runtime/src/adapter/getNativeAPI.js
- packages/jsx2mp-runtime/src/adapter/setComponentRef.js
- packages/jsx2mp-runtime/src/bridge.js
- packages/jsx2mp-runtime/src/component.js
- packages/jsx2mp-runtime/src/createRef.js
- packages/jsx2mp-runtime/src/getId.js
- packages/jsx2mp-runtime/src/page.js
- packages/jsx2mp-runtime/src/updater.js
- 重构 ref 相关，所有表现和 rax core 对齐，并支持微信小程序
- 移除 __parentId
> refactor(jsx2mp): ref

- packages/miniapp-element/src/builtInComponents/picker-view.js
- packages/miniapp-element/src/templates/index.axml
- fix: avoid value attribute in picker-view be stringified
- feat: support using picker-view
> feat(miniapp): support using picker-view in runtime miniapp

- packages/jsx-compiler/src/modules/__tests__/condition.js
- packages/jsx-compiler/src/modules/condition.js
- packages/jsx-compiler/src/utils/handleList.js
- packages/jsx2mp-runtime/package.json
- packages/jsx2mp-runtime/src/bridge.js
- packages/jsx2mp-runtime/src/classnames.js
- Fix: Inserted property index
- Fix: condition insert check
- Fix: page options update
> fix(jsx2mp): list render

- packages/jsx-compiler/src/modules/__tests__/jsx-plus.js
- packages/jsx-compiler/src/modules/attribute.js
- packages/jsx-compiler/src/modules/list.js
- packages/jsx-compiler/src/utils/getExportComponentPath.js
- packages/jsx-compiler/src/utils/handleList.js
- packages/jsx-compiler/src/utils/handleListProps.js
- packages/jsx-compiler/src/utils/handleRefAttr.js
- packages/jsx-compiler/src/utils/handleValidIdentifier.js
- packages/jsx-compiler/src/utils/isClassComponent.js
- packages/jsx-compiler/src/utils/isNativeComponent.js
- packages/jsx2mp-runtime/src/bridge.js
- packages/jsx2mp-runtime/src/router.js
- packages/jsx2mp-runtime/src/updater.js
- Fix complier `withRouter` complie error
- Fix runtime `withRouter` is invaild
- Fix ref in list
> fix(jsx2mp): with router

- packages/driver-dom/package.json
- packages/driver-dom/src/__tests__/css-unit-operations.js
- packages/driver-dom/src/index.js
- packages/rax-server-renderer/src/__tests__/renderToString.js
- packages/rax/src/__tests__/createContext.js
Fix the different style order between client and server.  This is because style is deleted by mistake.
> fix: style order when hydating style

- packages/rax-document/package-lock.json
- packages/rax-document/src/index.js
- packages/rax-server-renderer/src/__tests__/renderToString.js
- packages/rax/src/__tests__/createContext.js
rax-scripts: https://github.com/raxjs/rax-scripts/pull/220
add manifest meta
> feat: document add manifest

- packages/rax-app/package.json
- packages/rax-app/src/page.js
Fix  `weex.requireModule('globalEvent')` to `require('@weex-module/globalEvent');`
> Fix weex requireModule

- .travis.yml
> fix: publish before bench

- packages/jsx-compiler/src/modules/attribute.js
- packages/jsx-compiler/src/modules/element.js
- packages/jsx2mp-runtime/src/bridge.js
非原生事件也会经过事件代理，而 event 对象相关的操作，其实只是针对原生小程序事件
> fix(jsx2mp): custom event

- packages/miniapp-render/package.json
- packages/miniapp-render/src/node/style.js
- Refactor of the syle get and set way in element, which makes the style string matchs the setted order.
> refactor(miniapp): style get and set way changes to match web standard

- packages/miniapp-render/package.json
- packages/miniapp-render/src/index.js
> feat(miniapp): add create app

- packages/jsx-compiler/src/modules/__tests__/attribute.js
- packages/jsx-compiler/src/modules/attribute.js
- packages/jsx-compiler/src/modules/components.js
- packages/jsx-compiler/src/modules/jsx-plus.js
- packages/jsx-compiler/src/utils/handleRefAttr.js
> chore(jsx2mp): compatible with wechat miniprogram id

- packages/jsx-compiler/src/modules/__tests__/list.js
- packages/jsx-compiler/src/utils/handleList.js
- packages/jsx-compiler/src/utils/handleListJSXExpressionContainer.js
- packages/jsx-compiler/src/utils/handleListProps.js
- packages/jsx-compiler/src/utils/handleListStyle.js
- packages/jsx-compiler/src/utils/handleParentListReturn.js
> fix(jsx2mp): nested loop in map function

- packages/jsx2mp-runtime/package.json
- packages/jsx2mp-runtime/src/bridge.js
- packages/jsx2mp-runtime/src/component.js
- packages/jsx2mp-runtime/src/nativeEventListener.js
1. Fix onShareAppMessage is invaild
2. Fix `this.state`  in  `this.setState` callback
> fix(jsx2mp): share message

- packages/jsx2mp-runtime/package.json
- packages/jsx2mp-runtime/src/adapter/getComponentBaseConfig.js
- packages/jsx2mp-runtime/src/adapter/getNativeComponentLifecycle.js
- packages/jsx2mp-runtime/src/bridge.js
Support rax component that respond to props changes in native projects
> feat(jsx2mp): support reactive outer props

- packages/jsx-compiler/src/modules/condition.js
当使用 `a && b` 渲染的时候，直接跳过不处理。只处理 `a && <View></View>` 之类的情况。从而解决循环中，渲染 `item.a && item.a.b` 时，`item.a` 为 undefined 会报错的问题。
> fix(jsx2mp): logic expression render

- packages/jsx2mp-runtime/src/adapter/setComponentRef.js
- packages/jsx2mp-runtime/src/bridge.js
- packages/jsx2mp-runtime/src/component.js
- Without any optimized condition, when parent rerendered, its children should be rerendered too.
- Opitimize this.state structure
> fix(jsx2mp): when parent rerender child should rerender

- packages/rax-app/package.json
- packages/rax-app/src/app.js
Add error message when app error
> fix(rax-app): add error message

- packages/jsx2mp-runtime/src/component.js
> refactor(jsx2mp): use $batchedUpdates when setData in Alibaba MiniApp

- packages/jsx-compiler/src/adapter.js
- packages/jsx-compiler/src/baseComponents.js
- packages/jsx-compiler/src/getCompiledComponents.js
- packages/jsx-compiler/src/modules/components.js
- packages/jsx2mp-runtime/package.json
- packages/jsx2mp-runtime/rollup.config.js
- packages/jsx2mp-runtime/scripts/platform-plugin.js
- packages/jsx2mp-runtime/src/adapter/getComponentBaseConfig.js
- packages/jsx2mp-runtime/src/adapter/getNativeAPI.js
- packages/jsx2mp-runtime/src/adapter/getNativeComponentLifecycle.js
- packages/jsx2mp-runtime/src/adapter/setComponentRef.js
- packages/jsx2mp-runtime/src/component.js
- packages/jsx2mp-runtime/src/createRef.js
- packages/jsx2mp-runtime/src/router.js
> feat(miniapp): complier & runtime support bytedance

- packages/rax-document/package.json
- packages/rax-document/src/index.js
Pass props to script tag, eg:
```js
<Script crossorigin="anonymous" />
```
> feat: support pass props to script tag

- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/modules/list.js
- packages/jsx-compiler/src/modules/rax-slider.js
- packages/jsx-compiler/src/utils/handleListJSXExpressionContainer.js
- packages/jsx-compiler/src/utils/handleListProps.js
- packages/jsx-compiler/src/utils/handleListStyle.js
- Fix: map return the expression which isn't a JSXElement
- Fix: rax-slider render with map loop
> fix(jsx2mp): complier errror

- packages/miniapp-element/package.json
- packages/miniapp-element/src/builtInComponents/checkbox-group.js
- packages/miniapp-element/src/builtInComponents/checkbox.js
- packages/miniapp-element/src/builtInComponents/input.js
- packages/miniapp-element/src/builtInComponents/label.js
- packages/miniapp-element/src/builtInComponents/navigator.js
- packages/miniapp-element/src/builtInComponents/radio-group.js
- packages/miniapp-element/src/builtInComponents/radio.js
- packages/miniapp-element/src/builtInComponents/rich-text.js
- packages/miniapp-element/src/component.js
- packages/miniapp-element/src/templates/index.axml
- packages/miniapp-element/src/templates/index.wxml
> feat(miniapp): support alipay basic components

- packages/jsx2mp-runtime/package.json
- packages/jsx2mp-runtime/src/adapter/attachRef.js
- packages/jsx2mp-runtime/src/bridge.js
- packages/jsx2mp-runtime/src/component.js
- packages/jsx2mp-runtime/src/forwardRef.js
- packages/jsx2mp-runtime/src/hooks.js
- packages/jsx2mp-runtime/src/index.js
- packages/jsx2mp-runtime/src/types.js
- packages/rax/src/index.d.ts
Support `useImperativeHandle` & `forwardRef`
> feat(jsx2mp): support useImperativeHandle & forwardRef

- README.md
> docs: update driver spec link

- packages/jsx2mp-runtime/src/cycles.js
- packages/jsx2mp-runtime/src/nativeEventListener.js
appx2.0 原生事件生命周期发生 break change，针对该变动进行兼容
> chore: compatiblity appx2.0

- packages/rax/src/vdom/__tests__/empty.js
- packages/rax/src/vdom/empty.js
- packages/rax/src/vdom/instantiateComponent.js
> fix: render returns null to null empty nodes are also rebuilt(#1830)

- packages/jsx2mp-runtime/src/component.js
- fix the bug that $spliceData is not uesd in alipay miniapp
> fix(jsx2mp): use shallowEqual to judge array item

- packages/jsx2mp-runtime/src/adapter/attachRef.js
- packages/jsx2mp-runtime/src/bridge.js
- packages/jsx2mp-runtime/src/component.js
- packages/jsx2mp-runtime/src/createRef.js
- packages/jsx2mp-runtime/src/hooks.js
- 修复 ref 在微信上的表现
- 新增支持微信小程序`useImperativeHandle`
> fix(jsx2mp): useImperativeHandle in wechat miniprogram

- packages/jsx2mp-runtime/src/component.js
> fix(jsx2mp): data update

- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/adapter.js
- packages/jsx-compiler/src/modules/__tests__/element.js
- packages/jsx-compiler/src/modules/element.js
- fix(jsx2mp): click event on rax-view/text not transformed to bindtap in wechat
> fix(jsx2mp): click event in rax-view/text in wechat

- packages/miniapp-element/package.json
- packages/miniapp-element/src/builtInComponents/input.js
- packages/miniapp-element/src/builtInComponents/navigator.js
- packages/miniapp-element/src/builtInComponents/rich-text.js
- packages/miniapp-element/src/builtInComponents/textarea.js
- packages/miniapp-element/src/builtInComponents/video.js
- packages/miniapp-element/src/templates/index.axml
- packages/miniapp-element/src/templates/inner-component.axml
- Fix textinput onchange event
- Fix picker-view render
- Fix missing property in 10th view node
- Feat support enableNative attr for video tag in dingTalk
> [BETA] miniapp-element beta for release/miniapp-0608

- packages/miniapp-render/src/builtInComponents/input.js
- packages/miniapp-render/src/builtInComponents/map.js
- packages/miniapp-render/src/builtInComponents/movable-view.js
- packages/miniapp-render/src/builtInComponents/picker-view.js
- packages/miniapp-render/src/builtInComponents/picker.js
- packages/miniapp-render/src/builtInComponents/scroll-view.js
- packages/miniapp-render/src/builtInComponents/swiper.js
- packages/miniapp-render/src/builtInComponents/switch.js
- packages/miniapp-render/src/builtInComponents/textarea.js
- packages/miniapp-render/src/createConfig/custom.js
- packages/miniapp-render/src/document.js
> feat: support with zero config use native custom compnent

- packages/miniapp-render/src/bridge/lifeCycleAdapter.js
- packages/miniapp-render/src/createConfig/custom.js
- 修复微信、支付宝小程序中原生组件 props 发生变化时无法响应的问题
> fix(miniapp): can't get props update in native component

- packages/miniapp-render/__tests__/document.test.js
- packages/miniapp-render/__tests__/node/class-list.test.js
- packages/miniapp-render/__tests__/node/element.test.js
- packages/miniapp-render/__tests__/node/element/image.test.js
- packages/miniapp-render/__tests__/node/style.test.js
- packages/miniapp-render/__tests__/node/text-node.test.js
- packages/miniapp-render/renderMock.js
- packages/miniapp-render/src/node/element.js
- packages/miniapp-render/src/node/text-node.js
> fix(miniapp): miniapp render test

- packages/miniapp-render/src/createConfig/custom.js
- packages/miniapp-render/src/createConfig/page.js
- packages/miniapp-render/src/document.js
- packages/miniapp-render/src/node/root.js
When using 'DEBUG=true npm run start', every setData action cost time will be recorded
> feat(miniapp): support add perf

- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/adapter.js
- packages/jsx-compiler/src/modules/__tests__/attribute.js
> chore: rollback key complier

- packages/miniapp-render/package.json
- packages/miniapp-render/rollup.config.js
- packages/miniapp-render/src/createConfig/page.js
- packages/miniapp-render/src/node/root.js
> fix(miniapp): can't unmount component instance when unload page

- packages/miniapp-render/package.json
- packages/miniapp-render/rollup.config.js
- packages/miniapp-render/src/createConfig/page.js
- packages/miniapp-render/src/node/root.js
> build(miniapp-render): publish version 1.0.1

- 404.html
- index.html
* Update 0.6.1 -> 0.6.2
* Add IceWorks
> Feat rax.js.org update js resource version

- packages/miniapp-render/src/builtInComponents/canvas.js
- packages/miniapp-render/src/builtInComponents/input.js
- packages/miniapp-render/src/builtInComponents/movable-view.js
- packages/miniapp-render/src/builtInComponents/picker-view.js
- packages/miniapp-render/src/builtInComponents/picker.js
- packages/miniapp-render/src/builtInComponents/scroll-view.js
- packages/miniapp-render/src/builtInComponents/slider.js
- packages/miniapp-render/src/builtInComponents/swiper.js
- packages/miniapp-render/src/builtInComponents/switch.js
- packages/miniapp-render/src/builtInComponents/textarea.js
- packages/miniapp-render/src/builtInComponents/video.js
- packages/miniapp-render/src/builtInComponents/view.js
- packages/miniapp-render/src/node/attribute.js
- packages/miniapp-render/src/node/element.js
- packages/miniapp-render/src/node/root.js
- Fix: canvas width/height
- Fix: wechat miniprogram picker
> fix: base component

- packages/miniapp-render/src/builtInComponents/scroll-view.js
- packages/miniapp-render/src/node/element.js
1. Chore: remove useless methods
2. Fix: scroll-view scroll top/left value diff
> fix(miniapp): wechat miniprogram scroll props

- packages/rax-redux/README.md
- packages/rax-redux/package.json
> chore: release rax-redux

- packages/miniapp-render/package.json
- packages/miniapp-render/src/builtInComponents/index.js
- packages/miniapp-render/src/createConfig/page.js
> fix(miniapp): render bug in miniapp-render

- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/modules/__tests__/components.js
- packages/jsx-compiler/src/modules/components.js
> feat(jsx-compiler): support exporting multiple components

- examples/app-lifecycle/abc.json
- examples/page-lifecycle-with-router/abc.json
- examples/page-lifecycle-with-router/src/pages/About/index.jsx
- examples/page-lifecycle-with-router/src/pages/Home/index.jsx
- examples/with-miniapp-native-custom-component/abc.json
- examples/with-miniapp-native-page/abc.json
- examples/with-miniapp-plugin-component/abc.json
- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/modules/components.js
> chore: remove sensitive info in examples

- README.md
Feat update readme rax extension to iceworks.
> Feat update readme rax extension to iceworks

- packages/miniapp-render/package.json
- packages/miniapp-render/src/constants.js
- packages/miniapp-render/src/node/element/custom-component.js
- 支持钉钉小程序内置组件 open-avatar
- 修复小程序自定义组件配置 className 失败的问题
> feat(miniapp): support open-avatar

- packages/rax-server-renderer/package.json
- packages/rax-server-renderer/src/__tests__/styles.js
- packages/rax-server-renderer/src/index.js
Fix rpx transform in SSR, like: `transform:"translate3d(200rpx, 0, 0)"`
> fix: transform value with rpx

- packages/driver-dom/package.json
- packages/driver-dom/src/index.js
- packages/driver-universal/package.json
- packages/driver-weex/package.json
- packages/driver-worker/package.json
- packages/rax-set-native-props/package.json
- packages/style-unit/package.json
* 升级 style unit 版本以便同步到天马
* 修复 driver-dom umd 构建问题
> Sync style unit

- packages/rax-app/package.json
- packages/rax-app/src/index.js
- scripts/check-and-publish.js
背景是 https://github.com/alibaba/ice/blob/master/packages/rax-app-renderer/src/renderer.tsx#L66 这里新增了一个方法，然后老工程没有兼容
> fix: setAppConfig is not a function

- packages/rax/src/vdom/updater.js
> fixed: typo

- package.json
Close https://github.com/alibaba/rax/security/dependabot/package.json/axios/open
> chore: upgrade ci axios

- scripts/check-and-publish.js
Set tag to publisher, current tag is undefined.
> fix: auto publisher tag

- packages/rax/src/hooks.js
> fix: notes error

- packages/driver-weex/CHANGELOG.md
- packages/driver-weex/package.json
- packages/driver-weex/src/index.js
Add support to wee v2 in driver-weex
> feat: Support Weex v2

- packages/driver-universal/CHANGELOG.md
- packages/driver-universal/package.json
- packages/driver-universal/src/index.js
- scripts/dist-core.js
目前来看其它端的 driver 引入没有副作用，可以改为直接用 `import` 引入
> chore: use import instead of require

- README.md
> 📄 Update Text/Grammer in README.md

- packages/style-unit/CHANGELOG.md
- packages/style-unit/package.json
- packages/style-unit/src/index.js
修复 Node 环境下转换 rpx 到 vw 的流程，以支持 SSR 场景的 rax-compat 转换。
> fix: fix transform rpx error in node env.

- packages/rax-get-element-by-id/CHANGELOG.md
- packages/rax-get-element-by-id/package.json
in case of duplicate package version deps.
> chore:bump-universal-env-version
