alibaba/rax

packages/rax-cli/src/generator/templates/public/index.html
link and fix #68 
Trying to following the step in the readme file,
1. `rax init myDemo` after fresh install
2. run `cd myDemo && npm run start` 
3. open `localhost:8080` but get this error from debug tool
This is broken with the latest version of `web-rax-framework` which is loaded from https://unpkg.com/web-rax-framework@0.1.0/dist/framework.web.js
However an older version(0.0.10) https://unpkg.com/web-rax-framework@0.0.10/dist/framework.web.js (which is the one used on [rax playground](http://rax.taobaofed.org/playground/)) seems work without any issue.
This is because the bundled source code is using `define` which is not available yet.
```
// {"framework" : "Rax"}
define("framework.web", function(require) {/******/ (function(modules) { // webpackBootstrap
```
Tested with 0.1.2 and …
=> build: use webpack-rax-framework v0.1.2 cdn for rax-cli

packages/rax-cli/src/generator/index.js
Use [yarn](https://github.com/yarnpkg/yarn) if possible, fallback to npm when yarn is not installed.
=> feat: support yarn

README.md
- Amend ssr code https://github.com/taobaofed/server-side-rendering-comparison/pull/3 https://github.com/taobaofed/server-side-rendering-comparison/pull/4
- Replace opt/s by ms. Because I think `ms` can't transform to `opt/s` in this situation.
=> docs: update ssr data

docs/README.md
=> chore: Fix link in docs

packages/rax-cli/src/generator/templates/webpack.config.js
Fixed https://github.com/alibaba/rax/issues/114
Prefixing `@` style
```js
/*
//@ sourceMappingURL=[url]
*/
```
=> fix: source-map should in comment block

packages/stylesheet-loader/src/BoxModelPropTypes.js, packages/stylesheet-loader/src/FlexboxPropTypes.js, packages/stylesheet-loader/src/PropTypes.js, packages/stylesheet-loader/src/Validation.js, packages/stylesheet-loader/src/__tests__/particular.js, packages/stylesheet-loader/src/index.js, packages/stylesheet-loader/src/particular.js, packages/stylesheet-loader/src/transformer.js
* add position information
* remove vendor prefix
* not output `console` when no error or warn messages
* propType list add `display` and `flex`
* more field information 
```sh
line: 12, column: 3 - "z-index: 2" is not valid in ".item" selector
```
=> More friendly stylesheet loader

packages/rax-webpack-plugin/package.json, packages/rax-webpack-plugin/src/PlatformLoader.js, packages/rax-webpack-plugin/src/TraverseImport.js, packages/rax-webpack-plugin/src/__tests__/TraverseImport.import.js
1. The `PlatformLoader` ought to return code and sourcemap that the  `TraverseImport` produce.
2. The sourcemap should merge the `inputSourceMap` that previous loader produce
=> fix: fix sourcemap logic of multi config

packages/babel-plugin-transform-jsx-stylesheet/src/__tests__/index.js, packages/babel-plugin-transform-jsx-stylesheet/src/index.js
这里使用 const 最终不会转成 var，因为 plugin 永远在 loader 后面执行的
=> Use var replace const in plugin

packages/babel-plugin-transform-jsx-stylesheet/package.json
camelcase 4.0.0 没有编译，在 playground 中不能使用
=> Change camelcase version

packages/rax-switch/src/index.js
增加switch  props 透传，修复以下问题：
switch 组件 re-render 时，（特别是删除 dom 后），由于没有传 key ， native 查找节点时根据 id 先后来查找 dom，出现没被操作的 switch  出现动画的诡异的现象。
bug demo 参考：
https://alibaba.github.io/rax/playground/a5051f48-5887-4a60-ab39-09626e9f15a9
=> fix : switch component add ... other props

packages/rax-webpack-plugin/src/MultiplePlatform.js, packages/rax-webpack-plugin/src/__tests__/MultiplePlatform.js
It should config like [this](https://github.com/webpack/webpack/blob/master/examples/multi-compiler/webpack.config.js#L5)
eg:
when webpack returns stats object , it need this property [ref](https://github.com/webpack/webpack/blob/master/lib/MultiStats.js#L46-Lundefined)
=> chore: add config name to identify container type in compilation process

packages/rax/src/vdom/__tests__/composite.js, packages/rax/src/vdom/composite.js, packages/rax/src/vdom/empty.js, packages/rax/src/vdom/fragment.js, packages/rax/src/vdom/instance.js, packages/rax/src/vdom/native.js, packages/rax/src/vdom/text.js
Components can use `componentDidCatch` method to catch errors.
```
class App extends Component {
render() {
return (
<div className="App">
<ErrorBoundary>
<BrokenRender />
</ErrorBoundary>
</div>
);
}
}
class ErrorBoundary extends Component {
state = {error: null};
componentDidCatch(error) {
this.setState({error});
}
render() {
if (this.state.error) {
return (
<Text>{`Caught an error: ${this.state.error.message}.`}</Text>
);
}
return this.props.children;
}
}
function BrokenRender(props) {
throw new Error('BrokenRender');
}
```
=> support error boundary

.babelrc, package.json, packages/rax/src/index.js
`rax` 目前没有 export default，当用户在 webpack 中配置 `alias` 使用 rax 替代 react 时，原有的
```js
import React from 'react';
```
往往不能运行。
```js
import React from 'react';
import Rax from 'rax';
import { createElement } from 'rax';
console.log(React); // React
console.log(Rax);  // undefined
console.log(React.Children); // React.Children
console.log(createElement); // rax.createElement
```
https://www.webpackbin.com/bins/-KtjqtZKIyTSU6Lp7QKb
同时直接使用 `React.Children.only` 等函数的代码也无法使用
=> fix: export default rax and rax.Children

packages/universal-jsonp/src/index.js
Removing script tag will not abort the request, so remove callback function directly will cause this issue.
=> fix: solve the 'Uncaught ReferenceError: callback_*** is not defined' error on web for universal-jsonp

packages/weex-rax-framework/src/__tests__/index.js, packages/weex-rax-framework/src/index.js
通过globalEvent的exception类型事件来触发。
会按照w3c的onerror回调来提供 message，source，行列号（暂定为0），err对象。
提供和w3c类似的api，业务代码里可以通过
```
window.onerror = (e) => {
if ( typeof WXEnvironment !== 'undefined' ) {
let instanceWrap = require('@weex-module/instanceWrap');
instanceWrap && instanceWrap.error && instanceWrap.error(1, 1004, 'Downgrade[occur error] :: error info ' + e); 
}
}
```
在业务稳定之后，对weex页面发生不在预料之中的错误时进行单点被动降级。
=> 为weex下增加w3c标准的onerror API

packages/rax-canvas/src/index.js
没有默认值，造成 https://github.com/alibaba/rax/blob/master/packages/rax-qrcode/src/index.js#L44 渲染失败。
=> fix: rax-canvas context must has type, default 2d

packages/web-rax-framework/src/appearRegistry.js
I have a case, use rax in ie, if el.parentNode === null,  mean el is node added to document, 
call getBoundingClientRect will throw error, another browser return { top: 0, right: 0... }
=> Fix a bug in ie

packages/stylesheet-loader/src/CSSTransitionPropTypes.js, packages/stylesheet-loader/src/Validation.js, packages/stylesheet-loader/src/__tests__/particular.js, packages/stylesheet-loader/src/particular.js
`Weex v0.1.16+` 已经支持CSS动画的书写方式，具体见 [transition](http://weex-project.io/cn/wiki/common-styles.html#can-shu)，`Rax` 需要调整代码才可以支持
* `transition`
* `transition-property`
* `transition-duration`
* `transition-delay`
* `transition-timing-function`
**客户端不支持秒的单位，设置 `0.5s` 不会被运行**
```
transition-duration: 0.3s => 300ms
transition-delay: .2s => 200ms
```
```
transition-property: all => width,height,top,bottom,left,right,backgroundColor,opacity,transform
```
`Weex` 中背景的写法是**驼峰**的 `backgroundColor`，不符合样式的书写习惯，这里修改兼容**中划线**的写法 `background-color`
```
transition-property: background-color => backgroundColor
```
```
transition: width 0.5s linear .2s
=>
transition-property: width;
transition-duration: 500ms;
transition-delay: 200ms;
transition-timing-function: linear;
```
=> Feat: Support css transition

packages/rax-server-renderer/README.md, packages/rax-server-renderer/src/index.js
config rem ratio in rax ssr
usage
```jsx
import {createElement, Component} from 'rax';
import renderer from 'rax-server-renderer';
class MyComponent extends Component {
render() {
return <div>Hello World</div>;
}
}
renderer.renderToString(<MyComponent />, {
remRatio: 100
});
```
config the web template meanwhile
```js
var remUnit = document.documentElement.clientWidth / 750;
document.documentElement.style.fontSize = remUnit * 100 + 'px';
```
=> feat: add rem ratio config

components/rax-image/src/index.d.ts
load: (event: ImageLoadEvent) => void; -> load?: (event: ImageLoadEvent) => void;
否则会在ts下提示load必传的报错
=> rax-image load参数默认可以不传

components/rax-textinput/src/index.d.ts
rax-textinput 的 index.d.ts 引用 BaseProps 有误，导致在 ts 中 rax-textinput 使用 style 属性会报错
=> fix: rax-textinput index.d.ts 中 BaseProps 引用错误

packages/miniapp-manifest-loader/README.md, packages/miniapp-manifest-loader/package.json, packages/miniapp-manifest-loader/src/index.js
将 manifest 作为 entry 转换成 js 代码
- 支持实时编辑
- 加载 pages/page/index.html
后调用 miniapp-web-renderer 渲染
=> feat: miniapp-manifest-loader

packages/rax/src/vdom/__tests__/composite.js, packages/rax/src/vdom/composite.js
一般情况下 null 等 都要注释节点兜底，所以composite renderComponent diff的时候不会报错，但是frag情况下，如果空数组实际不会生存node节点 所以会出错
[复现demo](https://codepen.io/anon/pen/jvQjyg?editors=0111)
=> fix: composite diff error

packages/mp-loader/src/transpiler/transpileModules/index.js
`<view a:for="{{[1, 2, 3]}}" a:if="{{item == 1}}"></view>`
之前被编译成了 
```js
_l.call(this, [1, 2, 3], function (item, index) {
return data.item == 1 ? xxx : yyy;
});
```
修复效果 
```js
_l.call(this, [1, 2, 3], function (item, index) {
return item == 1 ? xxx : yyy;
});
```
=> fix: mp-loader a:for item scope can not use in a:if

packages/rax/src/vdom/__tests__/fragment.js, packages/rax/src/vdom/fragment.js
对fragment中的冗余逻辑进行删除，实际上 fragment的 _parent是不可能为 array类型的，因为fragment每次创建孩子节点的时候把自己的_parent传递下去， 而且fragment的_parent为array的话，也会和native中的逻辑造成bug  [相关代码](https://github.com/alibaba/rax/blob/master/packages/rax/src/vdom/native.js#L382)
=> refactor: remove redundant  code

packages/mp-loader/src/transpiler/transpileModules/index.js, packages/mp-loader/src/transpiler/transpileModules/key.js
`<view a:for="{{xx}}" a:key="{{item.id}}">`  a:key 被转换为 { key: item.id }
=> fix: support a:key for mp

packages/rax/src/__tests__/createContext.js, packages/rax/src/createContext.js
兼容React new Context的API设计的非常巧妙，但是这里会两重问题
1. 在Provider value 改变的时候，实际会触发两次Consumer的更新。
2. Consumer更新的顺序无法保证
React16不会出现这两个问题，new Context的难点在于，如何保证在Parent不更新情况下，他的子代的Consumer能触发更新，React16可以非常容易的实现这一点，再Provider的value更新的时候，propagateContextChange去修改依赖的Consumer的expirationTime，再往上更新其return fiber的childExpirationTime的值即可。propagateContextChange不会立即触发Consumer的更新，只是修改了它的expirationTime。 这样就能确保，当前的渲染流程中，无论Consumer的parent是否会更新，借助react16的fiber的reconciler机制，Consumer都会更新，而且只更新一次
rax是stack reconciler, Parent的不更新，就会造成child的不更新，所以使用了event机制作为解决方案。如何在当前方案下面去解决这两个问题？基本的出发点是，同步往下传递最新的context value,  往后推迟event emit, 当event监听的事件触发的时候，判断当前Consumer是否已经取得最新的context value，如果不是的话，说明其ancestor有不更新情况，需要setState, 如果不是的话，Consumer就无需setState了
因为Consumer的一般来说, 其child function是定义在Owner组件里面的，可能使用了Owner组件里render函数的变量，所以必须保证Owner …
=> fix: Consumer render twice and render order incorrect

packages/mp-runtime/src/computeChangedData.js
case
```js
rawData: { title1: '', title2: '' };
this.setData({ title1: '1111' })
this.setData({ title2: '2222' })
```
原逻辑会变成 
```js
this.setState({ title1: '1111', title2: '' })
this.setState({ title1: '', title2: '2222' })
```
导致后面的覆盖了前面, 期望
```js
this.setState({ title1: '1111' })
this.setState({ title2: '2222' })
```
=> fix: get compute changed data

packages/render-helpers/src/renderStyle.js
```
<view style="background-image: url({{url}})" />
url = 'https://g.alicdn.com/foo.png';
```
--->
```
background-image: url(https;
```
```
_cx(style, null);
```
_cx 会把 cssText 转换成 cssObject (kv), 用正则切分 `:` 的时候没有考虑 background-image
=> fix: style object split work with background image url

universal/universal-transition/src/index.js
由于Web上设置transition-property为All，导致transition系统会控制不需要控制的style，造成多余的动画效果
=> fix: transition universal all bug

packages/mp-loader/src/index.js
如果缺少分号, 
```
App({})
```
末尾的括号会与下面的IIFE构成 CallExpression. 导致运行时报错.
```
App({})
(function(){ 
// ...
})();
```
所以必须单独加一个`;` 隔开
=> fix: allow app.js content not ended with `;`

universal/universal-transition/src/index.js
transition style格式错误
About: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions#Multiple_animated_properties_example
=> fix: wrong transition format

packages/rax/src/vdom/__tests__/composite.js, packages/rax/src/vdom/composite.js
目前的错误处理是同步渲染错误，但是rax的渲染模型是stack更新，所以这里会有问题
两个 比较直观的例子
[demo1](https://codepen.io/anon/pen/EGxVqW?editors=0111)
[demo2](https://codepen.io/anon/pen/yGLYmN?editors=0111)
一个是由于错误更新时候，栈信息的遗留，导致底部多了个sibling，一个是fragment的childMount机制，child只是mount，还没加入到parnetNode，就被拿去diff， 所以导致报错
这里修复的话，可以比较简单的异步去执行错误处理函数，但是同步渲染的模式下面，又多个个异步，可能对用户来说不太友好，希望能做到的是用户render时候，能同步获取到最新的状态
```
render(<App />); 
code // 无论是否发生错误，这里用户能拿到稳定的状态
```
用boundary去处理错误，所以我们在延迟在boundary didMount didUpdate稳定状态去同步刷新就可以了,
目前的错误回调直接放在了之前存在的callback里面，可能自己弄个captureCallback会更好
react16中对错误处理还有强制unmout机制，不过这些都是错误处理的策略问题了。
=> Fix boundary error handle

packages/atag/src/components/checkbox-group/index.js, packages/atag/src/components/text/index.js, packages/atag/src/components/view/index.js
把 text 组件的 shadow-dom 去掉了, 因为 slot 节点在浏览器下也算成一个节点, 处理样式继承需要走白名单, 从组件角度来看, text 组件本身没有什么依赖shadow dom 的逻辑
=> fix: checkbox and text

packages/rax/src/__tests__/createPortal.js, packages/rax/src/__tests__/render.js, packages/rax/src/vdom/__tests__/native.js, packages/rax/src/vdom/composite.js, packages/rax/src/vdom/instance.js, packages/rax/src/vdom/native.js
增加rax更新时的一些优化
在jsx的作用下，每次render的时候，新生成一个新的react element对象，这样的话，每次都会去执行更新diff,  在不可变的数据结构上面讲，这层逻辑面上面没错，两个不一样的element确实需要去更新，所以有pureComponet或者 Memo解决方案
但是，很多静态的东西我们想直接做一层，elemnt缓存，去解决性能问题的方案，但是相信很少人会这么写
```
const A = <div />
render(A) 
render(A)  // 期望不在执行任何diff操作 
```
虽然很少可能这么去写，但是无感于用户，element缓存可以在框架层面做，
比如react-redux最新版本中，用了这个策略 [相关代码](https://github.com/reduxjs/react-redux/blob/master/src/components/connectAdvanced.js#L171),  基于这个启发，感觉这个特性还是非常有用的
=> Feat update opt

packages/atag/src/components/image/index.js, packages/atag/src/components/map/map.native.js
统一用 camelcase 调用 api, 对 attribute 在创建节点的时候转换为 kebabCase
...
修复 安卓 调用 update 后会清除所有导航路径的问题: 在update 之后再调用一次 drawRoute
=> fix: native map android drop route after update

packages/mp-loader/package.json, packages/mp-loader/src/transpiler/__tests__/__snapshots__/template-transpiler.js.snap, packages/mp-loader/src/transpiler/__tests__/template-transpiler.js, packages/mp-loader/src/transpiler/expression.js, packages/mp-loader/src/transpiler/helpers.js
原先对  `xx={{[{}]}}` 的提取正则有问题, 用 `.*` + 贪婪模式 实现兼容 `xx="{{a}} {{b}}` 和 `xx="{{[ {} ]}}"`
=> fix: mp get array binding

package.json
eslint-plugin-react 发了个minor 位新版本不知道改了啥, 现在 lint 报错了, 先锁定到7.11.x
=> chore: eslint pass

packages/rax/src/__tests__/hooks.js, packages/rax/src/hooks.js, packages/rax/src/vdom/reactive.js
主要解决两个问题：
1. fix: useReducer
在rax之前的实现中，function每次渲染中，无论useReducer中的reducer参数是否改变，dispatcher始终引用了初始闭包里面的reducer。但是仔细观察官方的实现中，reducer实时引用的是function执行时候传入的reducer，真正缓存的应该是state，而不是reducer。也就是说useReducer计算nextState是在渲染时，拿到最新的reducer才去计算，而不是在dispatcher阶段去计算。由于这里存在异步渲染的关系，把action放入队列中
2. 另外一个问题是在function执行的过程中，调度更新如何处理的问题，这里已经完全覆盖了官方的相关test
=> Refactor hook

packages/atag/src/components/text/index.js
构建已经做了去空格和LF, 不需要在组件层面再做一遍.
组件层面做会导致动态拼接的 \n 也被干掉
=> fix: should not trim lf in text

packages/atag/src/components/scroll-view/__tests__/scroll-view.html, packages/atag/src/components/scroll-view/__tests__/scroll-view.js, packages/atag/src/components/scroll-view/index.js
prevent setter 不应该覆盖 this.scrollX 和 this.scrollY, 这样就没办法恢复了
=> fix: atag scroll-view scrollX/Y as property

README.md, packages/rax/src/__tests__/hooks.js, packages/rax/src/hooks.js, packages/rax/src/index.d.ts, packages/rax/src/index.js
官方已经把useImperativeMethods改成useImperativeHandle了，这里同步一下
[相关pr](https://github.com/facebook/react/pull/14565/files)
=> chore: rename useImperativeMethods -> useImperativeHandle

packages/atag/src/components/textarea/index.js
一些 textarea 默认的属性被 unset: all 覆盖了. 重新重置回来.
white-space 重置引起以下问题:
=> fix: atag textarea

packages/atag/src/components/text/index.js, packages/atag/src/components/view/index.js
=> fix: style atg use innerHTML

packages/atag/src/components/scroll-view/__tests__/nested.html, packages/atag/src/components/scroll-view/index.js
scroll-view 嵌套情况下, 浏览器会自动处理嵌套的滚动情况, 如果额外把父层节点 overflow hidden, 会导致滑动起来是卡顿的
=> fix: nested scroll-view

packages/rax/src/__tests__/hooks.js, packages/rax/src/hooks.js
hook的规范改了下，当无依赖的时候，effect或者memo等等的结果都需要更新。相关pr [pr1](https://github.com/facebook/react/pull/14594/files) [pr2](https://github.com/facebook/react/pull/14801/files)
useMemo中的preInputs一直是mount时候preInputs，这里修复了一下
增加了一些单测
=> Never memoize if no deps

packages/rax/src/__tests__/hooks.js, packages/rax/src/hooks.js, packages/rax/src/vdom/reactive.js
react16官方对hook这块的优化思路看着挺有意思的，能在函数进行render的时候，对children进行bail out
react16 render时候，进行bail out比较容易，不往下这些逻辑就行，目前在rax上面实现思路为
1. 通过 componentWillMount 和  componentWillReceiveProps 判断是否是通过父更新带来的更新
2. setState的时候，把所有的状态都存储在eagerState里面（因为都是同步优先级）
3. 导出状态的时候，和之前的判断是否发生改变
通过element缓存，来到达不更新children的效果
这块可能在bath update的时候，比较有用，如果后面有考虑提供这种api，或者在effect中使用的话
=> Hook update opt

.travis.yml, packages/mp-runtime/src/createComponent.js, packages/mp-runtime/src/createPage.js
不应该在 createPage 的时候直接插入元素.  
createPage 是返回页面组件, 这个时候真正的渲染生命周期还没有被触发，导致目前可能出现的样式丢失。
修复: 在页面被第一次 render 被调用的时候
=> fix: style render should be called in render, not in constructor

docs/en-US/driver-spec.md
The current link of [browse driver](https://github.com/alibaba/rax/blob/master/packages/driver-browser/src/index.js) is broken, I updated the link to the correct/new [dom driver](https://github.com/alibaba/rax/blob/master/packages/driver-dom/src/index.js)
=> fix broken link to `browser driver`

packages/rax/src/hooks.js
Current will exec twice when reducer direct set inner function component, this pr fix it:
```jsx
function init(initialCount) {
return {count: initialCount};
}
function App({initialCount}) {
const [state, dispatch] = useReducer(function reducer(state, action) {
// Only exec once when dispatch new state
console.log(action, state);
switch (action.type) {
case 'increment':
return {count: state.count + 1};
case 'decrement':
return {count: state.count - 1};
case 'reset':
return init(action.payload);
default:
throw new Error();
}
}, initialCount, init);
return (
<>
Count: {state.count}
<button
onClick={() => dispatch({type: 'reset', payload: initialCount})}>
Reset
</button>
<button onClick={() => dispatch({type: 'increment'})}>+</button>
<button onClick={() => dispatch({type: …
```
=> fix: reducer only exec once when reducer  set inner function component

packages/rax-scripts/src/config/webpack.config.js
In order to write Rax APP in TypeScript, .tsx files should be supported.
---
=> feat(rax-script): support .tsx files

packages/rax-scripts/src/config/path.config.js
The "--output-path" option of "rax-scripts" was not working. I've found the reason, and figured out a 
simple solution.
---
=> fix(rax-scripts): command line option "--output-path" not working

README.md, packages/rax-use-router/READMD.md, packages/rax-use-router/package.json, packages/rax-use-router/src/__tests__/index.js, packages/rax-use-router/src/index.js
history 的职责与浏览器里的 history 相同，rax-use-router 里的 push、replace、go 等同与 history：
```jsx
import { createElement, Fragment } from 'rax';
import { useRouter, push } from 'rax-use-router';
import { createHashHistory } from 'history';
import Foo from './Foo';
import NotFound from './NotFound';
const config = () => {
return {
history: createHashHistory(),
routes: [
// Static Component
{
path: '',
component: <>
<button onClick={() => push('/home')}>go home</button>
<button onClick={() => push('/404')}>go 404</button>
</>,
},
{
path: '/home',
routes: [
// Dynamic Component 
{
path: '',                  // www.example.com/home
component: () => <>
<button onClick={() => push('/foo')}>go foo</button>
<button onClick={() => push('/bar')}>go bar</button>
<button onClick={() => push('/home/jack')}>go …
```
=> rax-use-router with history

packages/rax/package.json, packages/rax/src/vdom/native.js
渲染性能：当前容器没有子元素时，直接 mountChildren ，跳过原有的比对
删除节点的性能：当父节点被 removeChild 后，子元素不再重复执行 removeChild
=> perf: improve creating & removing performace

packages/rax-dom/src/index.js, packages/rax/src/compat/index.js
默认导出default，不然会出现下面情况。
```js
import React, { useState } from 'react'
console.log(useState); // function
console.log(React); // undefined
```
driver-dom 引用有问题
```js
import DriverDOM from 'driver-dom';
// to
import * as DriverDOM from 'driver-dom';
```
=> fix: react compatibility

packages/mp-loader/package.json, packages/mp-loader/src/__tests__/__snapshots__/template-loader.js.snap, packages/mp-loader/src/extensionAdapter.js, packages/mp-loader/src/template-loader.js, packages/mp-loader/src/transpiler/__tests__/__snapshots__/ali-template-transpiler.js.snap, packages/mp-loader/src/transpiler/__tests__/__snapshots__/weixin-template-transpiler.js.snap, packages/mp-loader/src/transpiler/helpers.js, packages/mp-loader/src/transpiler/transformModules/__tests__/key.js, packages/mp-loader/src/utils.js
原先用了 `data` 这个作用域名与 props 中的 data 会有冲突, 即:
```
<Component data=“{{foo}}” />
```
In Component:
```
<view>{{data}}</view>
```
original: 
```
function render(data) {
return (createElement(‘view’, null, [data]));
}
```
> PS: 入参 `data = { …this.data, …this.props };` 
after:
```
function render(__data__) {
var data = __data__.data;
return (createElement(‘view’, null, [data]));
}
```
=> Fix mp loader data conflict

packages/postcss-plugin-rpx2vw/README.md, packages/postcss-plugin-rpx2vw/package.json, packages/postcss-plugin-rpx2vw/src/__tests__/index.js, packages/postcss-plugin-rpx2vw/src/index.js
- Unified `rpx` as standard unit.
- Eliminate the differences between web and universal.
```css
.a {
margin: -10rpx .5vh;
padding: 5vmin 9.5rpx 1rpx;
border: 3rpx solid black;
border-bottom-width: 1rpx;
font-size: 14rpx;
line-height: 20rpx;
}
.b {
border: 1rpx solid black;
margin-bottom: 1rpx;
font-size: 20rpx;
line-height: 30rpx;
}
```
```css
.a {
margin: -1.33333vw .5vh;
padding: 5vmin 1.26667vw 0.13333vw;
border: 0.4vw solid black;
border-bottom-width: 0.13333vw;
font-size: 1.86667vw;
line-height: 2.66667vw;
}
.b {
border: 0.13333vw solid black;
margin-bottom: 0.13333vw;
font-size: 2.66667vw;
line-height: 4vw;
}
```
=> feat: transform rpx to vw

packages/driver-dom/src/index.js, packages/driver-universal/package.json, packages/style-unit/package.json, packages/style-unit/src/index.js
修复 webkitLineClamp 不在白名单里导致数字类型值变 px 然后不生效的问题
=> fix: add webkitLineClamp whitelist

packages/rax-scripts/src/config/component/gulpfile-miniapp.js
=> fix: rax-scripts component-miniapp bug

packages/babel-plugin-transform-jsx-stylesheet/src/__tests__/index.js, packages/babel-plugin-transform-jsx-stylesheet/src/index.js
PC Rax 需要保存 className 以保证可以支持伪类的写法
=> feat: add dont remove className option

packages/rax-use-router/package.json, packages/rax-use-router/src/index.js
匹配路由时应该只需要匹配 pathname 即可，search 不需要强制匹配：
```javascript
// routers
[
{
path: '/search',
component: () => <Search />,
}
]
```
可以匹配到
http://localhost:9999/search
http://localhost:9999/search?q=xxx
http://localhost:9999/search?q=xxx&any_query=xxxx
当前版本无法匹配带 query 的情况。
=> fix: match search is not needed

packages/rax-plugin-app/src/plugins/PWAAppShellPlugin.js
Update PWAAppShellPlugin.js. Use webpack instead of babel transform. Supports import method and @core/xxx modules
=> Feat: update App Shell plugin

packages/rax-miniapp-renderer/package.json, packages/rax-miniapp-renderer/src/EventHandler.js, packages/rax-miniapp-renderer/src/MutationHandler.js
修复引入自定义组件情况下页面的 onPageScroll 不响应的问题, 主要原因 $$id 被覆盖
=> Fix miniapp renderer

packages/driver-dom/src/index.js
为了支持 rpx 需要去做一些计算, 判断里尽量不用正则, 另外加了个缓存
---
创建 1000 节点性能数据   
preact vs rax   
1. 不支持 rpx,  1.00 VS 1.05
2. 支持 rpx (优化前), 1.00 VS  1.37
3. 支持 rpx (优化后), 1.00 VS 1.10
=> refactor: improve driver dom performance for rpx

packages/rax-server-renderer/src/index.js, packages/rax/src/__tests__/createContext.js, packages/rax/src/createContext.js, packages/rax/src/vdom/reactive.js
之前的new context 之前走老的context, 每次new context 更新造成context更新，导致jsx缓存失效，造成全量更新，new context应该独立，保证组件更新粒度
=> Refactor new context

packages/jsx-compiler/src/modules/__tests__/element.js, packages/jsx-compiler/src/modules/element.js
修复收集 `<div attr={{ key: value }} />` 时 value 变成对象的问题, 看代码应该是手误
=> fix: collect dynamic identifier instead of object prop

packages/driver-dom/src/index.js, packages/rax/src/vdom/native.js
case: 当 updateComponent 的时候, nextChildren 为空, 对 nativeNode 的操作由原来的逐个从 prevChild 去移除变成直接从当前节点清除所有 children (目前仅 Web)
=> refactor: improve performance with clearing all children

packages/jsx2mp-cli/getWebpackConfig.js, packages/jsx2mp-cli/plugins/runtime.js, packages/jsx2mp-loader/package.json, packages/jsx2mp-loader/src/babel-plugin-rename-import.js, packages/jsx2mp-loader/src/file-loader.js, packages/jsx2mp-runtime/rollup.config.js
1. `requre('@weex-module')` 移除这类节点
2. jsx2mp target 适配多平台, 现在直接把 dist 文件复制到 npm/jsx2mp-runtime.js
=> fix: remove weex module requirement

packages/rax-server-renderer/src/__tests__/renderToString.js, packages/rax-server-renderer/src/index.js
before
React#renderToString x 1,170 ops/sec ±1.24% (86 runs sampled)
Rax#renderToString x 2,032 ops/sec ±1.24% (89 runs sampled)
Inferno#renderToString x 4,121 ops/sec ±1.06% (88 runs sampled)
after
React#renderToString x 1,177 ops/sec ±1.28% (83 runs sampled)
Rax#renderToString x 4,908 ops/sec ±1.49% (83 runs sampled)
Inferno#renderToString x 3,649 ops/sec ±10.91% (79 runs sampled)
=> perf: cache css value

packages/jsx-compiler/src/modules/code.js, packages/jsx2mp-loader/src/babel-plugin-rename-import.js, packages/jsx2mp-loader/src/file-loader.js, packages/jsx2mp-runtime/package.json
1. 解析 npm 依赖和依赖的依赖的路径, 支持微信, 如
```js
import { isMiniApp } from 'universal-env';
```
现在会直接解析成
```js
import { isMiniApp } from '../npm/universal-env/lib/index.js';
```
并且只有 `lib/index.js` 这一个文件会被复制到 dist (按需)
2. 复制同构组件的支付宝小程序实现部分时，只复制一级目录, 不整个复制, 解决微信会无脑编译所有文件(包括测试用例)导致报错的问题
=> Fix npm support

packages/rax-compile-config/package.json, packages/rax-compile-config/src/getRouteName.js, packages/rax-compile-config/src/index.js, packages/rax-plugin-app/package.json, packages/rax-plugin-app/src/config/getWebpackBase.js, packages/rax-plugin-app/src/config/web/setDev.js, packages/rax-plugin-app/src/config/weex/setBuild.js, packages/rax-plugin-app/src/plugins/UniversalDocumentPlugin.js, packages/rax-plugin-multi-pages/package.json, packages/rax-plugin-multi-pages/src/getEntries.js, packages/rax-plugin-multi-pages/src/index.js, packages/rax-plugin-ssr/package.json, packages/rax-plugin-ssr/src/ssr/setDev.js, packages/universal-app-shell-loader/src/index.js
1. Multi-pages support routeName config
2. Support internal weex app publish
=> [Feat] Multi pages support routeName

packages/jsx-compiler/src/modules/code.js, packages/jsx2mp-loader/src/babel-plugin-rename-import.js, packages/jsx2mp-loader/src/file-loader.js
1. 修复 `import foo from 'xxx/lib/ccc'` 这种直接寻找文件的引入方式
2. 修复 file-loader babel 解析 jsx 报错的问题
=> fix: search npm module and support plugins

packages/babel-plugin-transform-jsx-stylesheet/src/__tests__/index.js, packages/babel-plugin-transform-jsx-stylesheet/src/index.js
eg.
**Input**
```jsx
import { createElement, Component } from 'rax';
import './app.css';
class App extends Component {
render() {
return <div className="header1 header2" />;
}
}
```
**Output**
```jsx
import { createElement, Component } from 'rax';
import appStyleSheet from './app.css';
var _styleSheet = appStyleSheet;
class App extends Component {
render() {
return <div style={Object.assign({}, _styleSheet["header1"], _styleSheet["header2"])} />;
}
}
```
**Input**
```jsx
import { createElement, Component } from 'rax';
import './app.css';
class App extends Component {
render() {
return <div className="header" style={{
height: 100
}} />;
}
}
```
**Output**
```jsx
import { createElement, Component } from 'rax';
import appStyleSheet from './app.css';
var _styleSheet = appStyleSheet;
class App …
```
=> feat: prop style array to Object.assign

packages/rax/src/vdom/scheduler.js
+ Performance: Use while instead of foreach for a small performance boost. [jsperf](https://jsperf.com/while-foreach)
+ Packet size： Reduce 0.0058 KB
=> Optimize scheduler size and performance

packages/babel-plugin-transform-jsx-to-html/README.md, packages/babel-plugin-transform-jsx-to-html/package.json, packages/babel-plugin-transform-jsx-to-html/src/__tests__/index.js, packages/babel-plugin-transform-jsx-to-html/src/index.js, packages/rax-server-renderer/src/__tests__/renderToString.js, packages/rax-server-renderer/src/index.js
pre tansform jsx to html for better ssr performance.
input 
```jsx
<div className="container" style={style} onClick={onClick}>
<div>a {props.index}</div>
</div>
```
output
```js
[{
__html: "<div class=\\"container\\""
}, {
__attrs: {
style: style,
onClick: onClick
}
}, {
__html: ">"
}, [{
__html: "<div>"
}, "a ", props.index, {
__html: "</div>"
}], {
__html: "</div>"
}]
```
benchmark (use inline style, about 1000 nodes)
```bash
mean:0.883ms
React#renderToString x 1,132 ops/sec ±2.17% (84 runs sampled)
mean:0.315ms
Rax#renderToString x 3,173 ops/sec ±1.64% (86 runs sampled)
```
benchmark (use className, about 1000 nodes))
```bash
mean:0.626ms
React#renderToString x 1,598 ops/sec ±3.11% (82 runs sampled)
mean:0.099ms
Rax#renderToString x 10,101 ops/sec ±1.85% (83 runs sampled)
mean:0.075ms …
```
=> feat: tansform jsx to html

packages/driver-dom/src/index.js, packages/rax/src/hooks.js, packages/rax/src/types.js, packages/rax/src/vdom/instantiateComponent.js, packages/rax/src/vdom/native.js, packages/rax/src/vdom/shallowEqual.js, packages/rax/src/vdom/shouldUpdateComponent.js
1. use `textContent` instead of `innerHTML`
2. use isNull instead of `xxx === null`:   from `xxx===null` to `f(xxx)`, decrease 4 chars each call.
=> Apply some performance optimisation

scripts/compile.js
npm run build will release __mocks__ directory into lib folder and it will cause jest warning about duplicate Mock path.
=> build: npm run build ignore __mocks__ folder

packages/driver-dom/src/index.js, packages/driver-universal/src/__tests__/css-custom-properties.js, packages/driver-universal/src/dom.js
feat: driver-universal support CSS custom properties
=> feat: driver-universal support CSS custom properties

packages/jsx-compiler/src/modules/__tests__/jsx-plus.js, packages/jsx-compiler/src/modules/code.js, packages/jsx-compiler/src/modules/components.js, packages/jsx-compiler/src/modules/element.js, packages/jsx-compiler/src/modules/index.js, packages/jsx-compiler/src/modules/jsx-plus.js, packages/jsx-compiler/src/modules/list.js, packages/jsx-compiler/src/modules/style.js
=> fix: render style property in list

packages/jsx-compiler/src/modules/code.js, packages/jsx-compiler/src/modules/list.js, packages/jsx-compiler/src/modules/style.js, packages/jsx2mp-loader/src/app-loader.js, packages/jsx2mp-runtime/src/bridge.js, packages/jsx2mp-runtime/src/router.js
=> fix: path is not found

packages/rax/src/__tests__/fragment.js, packages/rax/src/vdom/composite.js, packages/rax/src/vdom/fragment.js
revert dcc7f2f
the original commit cause an bug
do not use arr.SHIFT() operation to array, because it will mutate the array itself.
=> fix: use for loop instead of while to avoid mutate array iteself

packages/jsx2mp-loader/src/babel-plugin-rename-import.js, packages/jsx2mp-loader/src/script-loader.js
=> fix: path problem in single js file and npm file (only work with npm)

packages/jsx-compiler/src/modules/code.js, packages/jsx2mp-cli/getWebpackConfig.js, packages/jsx2mp-loader/src/app-loader.js, packages/jsx2mp-loader/src/page-loader.js, packages/jsx2mp-runtime/src/app.js, packages/jsx2mp-runtime/src/bridge.js, packages/jsx2mp-runtime/src/history.js, packages/jsx2mp-runtime/src/index.js, packages/jsx2mp-runtime/src/page.js, packages/jsx2mp-runtime/src/router.js
Support new format of `app.js`.
```js
import { runApp } from 'rax-app';
import appConfig from './app.json';
runApp(appConfig);
```
compiled to:
```js
import { runApp } from "./npm/jsx2mp-runtime";
import appConfig from "./app.raw.json";
runApp(appConfig);
```
=> refactor: rework jsx2mp appjs

packages/rax/src/vdom/__tests__/composite.js, packages/rax/src/vdom/composite.js, packages/rax/src/vdom/updater.js
1. 目前的error boundary在子节点单独渲染发生错误的时候，不会触发didCapture
2. didMount和didUpdate里面setState, callback执行的时机不太对，导致获取的state有问题
3.  [renderedElement的判断](https://github.com/alibaba/rax/compare/master...yongningfu:remove-update-callbacks?expand=1#diff-491d95b1578e65172a7f04a6dfda3ce3L132) 和 
[update中的stash callback](https://github.com/alibaba/rax/compare/master...yongningfu:remove-update-callbacks?expand=1#diff-32b231d4eaa6be874ac2c072653c6763L46) 逻辑看起来没用处
4. gzip:  6.27 -> 6.21
=> fix: error boundary bug and remove useless code

README.md
npm init <initializer>  is available in npm 6+
=> chore: npm init with hint npm version

packages/rax-server-renderer/package.json, packages/rax-server-renderer/src/__tests__/attributes.js, packages/rax-server-renderer/src/__tests__/basic.js, packages/rax-server-renderer/src/__tests__/renderToString.js, packages/rax-server-renderer/src/attribute.js, packages/rax-server-renderer/src/index.js
SSR 下 attribute 渲染测试用例补充 & 问题修复
`<a href={false} />`
before
`<a href></a>`
after
`<a></a>`
`<div hidden={false} />`
before
`<div hidden></div>`
after
`<div></div>`
`<div hidden="hidden" />`
before
`<div hidden="hidden"></div>`
after
`<div hidden></div>`
`<div hidden="foo" />`
before
`<div hidden="foo"></div>`
after
`<div hidden></div>`
`<div hidden="" />`
before
`<div hidden=""></div>`
after
`<div></div>`
`<div hidden={0} />`
before
`<div hidden="0"></div>`
after
`<div></div>`
`<div hidden={['foo', 'bar']} />`
before
`<div></div>`
after 
`<div hidden></div>`
`<div hidden={10} />`
before
`<div hidden="10"></div>`
after
`<div hidden></div>`
`<a download={false} />`
before
`<a download></a>`
after
`<a></a>`
`<div className={false} />`
before
`<div class="false" />`
after
`<div />`
`<div …
=> Basic tests for ssr

packages/jsx-compiler/src/adapter.js, packages/jsx-compiler/src/modules/__tests__/attribute.js, packages/jsx-compiler/src/modules/attribute.js, packages/jsx-compiler/src/modules/components.js, packages/jsx-compiler/src/modules/element.js, packages/jsx2mp-loader/src/component-loader.js
微信等平台小程序通过 Web Components 实现的自定义组件，导致 style 和 class 等样式标准命名被过滤掉，从而无法设置 shadow-root 内部元素样式。此次提交通过 styleSheet 和 className 等命名绕过该限制。
=> feat: support multiple-platform-style

packages/rax-create-class/package.json, packages/rax-create-class/src/__tests__/createClass.js, packages/rax/package.json, packages/rax/src/vdom/__tests__/context.js, packages/rax/src/vdom/__tests__/reactive.js, packages/rax/src/vdom/element.js
```js
import PropTypes from 'prop-types';
const Link = ({ active, children, onClick }) => (
<button
onClick={onClick}
disabled={active}
style={{
marginLeft: '4px',
}}
>
{children}
</button>
);
Link.propTypes = {
active: PropTypes.bool.isRequired,
children: PropTypes.node.isRequired,
onClick: PropTypes.func.isRequired
};
render(<Link active={true}>Hello World</Link>);
```
And will print warning in console:
```
Warning: Failed prop type: The prop `onClick` is marked as required in `Link`, but its value is `undefined`.
```
=> feat: support props check

packages/rax-server-renderer/package.json, packages/rax-server-renderer/src/__tests__/basic.js, packages/rax-server-renderer/src/__tests__/hooks.js, packages/rax-server-renderer/src/index.js, packages/rax/src/__tests__/hooks.js, packages/rax/src/forwardRef.js, packages/rax/src/hooks.js, packages/rax/src/vdom/composite.js, packages/rax/src/vdom/reactive.js
before
`Uncaught TypeError: currentInstance.getHookID is not a function`
after
`Uncaught Error: Hooks can only be called inside a component.`
```jsx
const value = 0;
function MyComponent() {
return <span>{value}</span>;
}
let str = renderToString(<MyComponent />);
```
before
```jsx
<span></span>
```
after
```jsx
<span>0</span>
```
=> Add tests for hooks in SSR

packages/jsx-compiler/src/adapter.js, packages/jsx-compiler/src/baseComponents.js, packages/jsx-compiler/src/compiledComponents.js, packages/jsx-compiler/src/modules/__tests__/components.js, packages/jsx-compiler/src/modules/__tests__/list.js, packages/jsx-compiler/src/modules/attribute.js, packages/jsx-compiler/src/modules/components.js, packages/jsx-compiler/src/modules/element.js, packages/jsx-compiler/src/modules/list.js, packages/jsx2mp-cli/__tests__/component.js, packages/jsx2mp-runtime/src/bridge.js, packages/jsx2mp-runtime/src/component.js
1. 解决微信小程序 props 传值和支付宝不一致的问题
2. 去除增加无意义的 tagId
3. map 循环渲染补全参数, `array.map(() => <View></View>)` => `array.map((item, index) => <View></View>)`
=> feat: support wechat miniprogram

packages/rax/src/vdom/__tests__/composite.js, packages/rax/src/vdom/composite.js, packages/rax/src/vdom/performInSandbox.js, packages/rax/src/vdom/updater.js
Fix below code that will make rax update exception:
```
const App = () => {
const [data, setData] = useState('string');
console.log('Host.__isUpdating', shared.Host.__isUpdating);
return (
<div onClick={() => {
setData({ a: 2 });
}}>
Hello World
<span>{data}</span>
</div>
);
};
```
=> fix: update exception when rise a element type error

packages/jsx2mp-cli/getWebpackConfig.js
- exclude weex module when analyzing dependencies in miniapp
=> fix(miniapp): exclude weex module

packages/rax/src/__tests__/createElement.js, packages/rax/src/vdom/composite.js, packages/rax/src/vdom/element.js
In dev mode, rax will freeze props.
```
function Foo(props) {
props.foo = 1; // => throw error
}
```
=> chore: freeze props

packages/rax/src/__tests__/createElement.js, packages/rax/src/createElement.js
```jsx
const App = () => {
let thisProps = {};
return (
<View>
<View {...thisProps}>A</View>
<View {...thisProps}>B</View>
<View {...thisProps} a={1}>C</View>
<View {...thisProps}>D</View>
</View>
);
};
```
This code will output  D D C D.
The same object ‘thisProps’ will be assigned continuously, Assign 'children' value D to ''thisProps''
When the property childern exists in config, prevent the same reference.
=> Fix: prevent the same reference

packages/jsx-compiler/src/modules/__tests__/element.js, packages/jsx-compiler/src/modules/element.js, packages/jsx2mp-runtime/src/bridge.js, packages/jsx2mp-runtime/src/component.js, packages/jsx2mp-runtime/src/cycles.js, packages/jsx2mp-runtime/src/hooks.js, packages/jsx2mp-runtime/src/index.js, packages/jsx2mp-runtime/src/page.js
1. 修复页面生命周期回调被重复注册的问题
2. 增加支持: usePagePullDownRefresh, usePageReachBottom, usePageScroll,
useShareAppMessage, useTabItemTap
3. 修复微信小程序绑定参数中存在 _ 导致 bad attribute 的问题
=> fix: page lifecyle

packages/rax-use-interval/README.md, packages/rax-use-interval/package.json, packages/rax-use-interval/src/index.js, packages/rax-use-timeout/README.md, packages/rax-use-timeout/package.json, packages/rax-use-timeout/src/index.js
Why `useInterval`? `setInterval` will called even component is unmounted that make error happens, and `useInterval` will auto `clearInterval` before component will mount.
```jsx
import { createElement } from 'rax';
import useInterval from 'rax-use-interval';
function Example() {
const [count, setCount] = useState(0);
useInterval(() => {
setCount(count + 1);
}, 1000);
return <h1>{count}</h1>;
}
```
=> feat: add useInterval and useTimeout

packages/rax-set-native-props/package.json, packages/rax-set-native-props/src/index.js
`this.eventRegistry` 是以前 driver 里的代码，现在在 web 下报错了
=> fix: setNativeProps has not eventRegistry in web

packages/jsx-compiler/src/modules/__tests__/element.js, packages/jsx-compiler/src/modules/element.js, packages/jsx2mp-runtime/src/bridge.js, packages/jsx2mp-runtime/src/component.js, packages/jsx2mp-runtime/src/updater.js
1. 修复属性值为字符串时，子组件无法正常更新 props 的问题
2. 修复循环渲染组件，二级子组件实例 id 一样，props 错乱的问题
=> fix: loop component instance id

packages/jsx-compiler/src/modules/__tests__/function.js, packages/jsx-compiler/src/modules/function.js
Fix require weex-module not be removed in another function body.
=> fix: require function traverse

packages/jsx-compiler/src/modules/__tests__/components.js, packages/jsx-compiler/src/parser/__tests__/importedAndExported.js, packages/jsx-compiler/src/parser/index.js
Fix jsx2pm compile error `import * as Env from 'universal-env'`
=> fix: jsx2mp-compiler parse namespace import error

packages/jsx-compiler/src/modules/__tests__/jsx-plus.js, packages/jsx-compiler/src/modules/element.js, packages/jsx-compiler/src/modules/jsx-plus.js
支持 `x-for` 里对 `item/index` 相关的函数处理，兼容 `x-class`
```jsx
<View x-for={items} data-item={setDataset(item)}>
<Text x-class={{ selected: selected === index }}>{parse(item)}</Text>
</View>
```
处理结果见下：
=> feat: 支持 x-for 里函数 filter 功能

packages/jsx-compiler/src/modules/__tests__/condition.js, packages/jsx-compiler/src/modules/condition.js
以下场景编译会报错：
```jsx
function App(props) {
const { a, b, ...c } = props;
}
```
=> fix: object pattern rest element error

packages/jsx-compiler/src/modules/element.js
compile bugfix: `item.item._f0` => `item._f0`
=> fix: jsx2mp filter

.travis.yml
In node 12, eslint is not found:
=> ci: In node 12 env, eslint is not found

packages/rax-app/package.json, packages/rax-app/src/runApp.js
rax-app runApp method support set props to page component.
entry.js
```jsx
// app.js
import { runApp } from 'rax-app';
import appConfig from './app.json';
runApp(appConfig, {test: 'hi~'});
```
page component
```jsx
// pages/home/index.jsx
import { createElement } from 'rax';
export default function Home(props) {
console.leog(props.test);
return <p>{props.test}</p>;
}
```
PS: runApp pageProps option has Highest priority and must be an object.
=> feat: rax-app support set pageProps

packages/jsx2mp-cli/getWebpackConfig.js
`presets` 里直接写 `@babel/preset-react`，`babel-loader` 会到当前项目目录下查找 `@babel/preset-react`，当构建逻辑不在项目里的话，会出现找不到的错误
```
- build
- node_modules
- @babel/preset-react
- cli.js
- project
- src
- package.json
```
=> fix: jsx2mp-loader-babel-config

packages/rax-server-renderer/src/__tests__/elements.js, packages/rax-server-renderer/src/index.js
1. fix render empty object
```jsx
let EmptyComponent = {};
renderToString(<EmptyComponent />);
```
before: return `undefined`
now: throw error `renderToString: received an element that is not valid.` 
2. fix: render a div with dangerouslySetInnerHTML number
```jsx
const str = renderToString(
<div>
<span dangerouslySetInnerHTML={{__html: 0}} />
</div>
);
```
before: `<div><span></span></div>`
now: `<div><span>0</span></div>`
3. fix: render null single child
```jsx
const str = renderToString(
<div>{null}</div>
);
```
before: `<div></div>`
now: `<div></div>`
the result before is inconsistent with multiple children
```jsx
const str = renderToString(
<div>
{null}
{null}
</div>
);
```
`<div></div>`
=> Tests for render elements in SSR

packages/driver-universal/README.md, packages/driver-universal/package.json, packages/driver-universal/src/weex.js
The following code, click the button, the height of the View will be changed by state update. However, it does not work properly under Weex.
Fixed a bug that `driver-universal` always remained，setStyle does not update with rpx.
```jsx
import { createElement, render, useState } from 'rax';
import DriverUniversal from 'driver-universal';
import * as DriverWeex from 'driver-weex';
import Text from 'rax-text';
import View from 'rax-view';
function App() {
const [flag, setFlag] = useState(true);
const style1 = {
width: '300rpx',
height: '500rpx',
backgroundColor: 'green',
overflow: 'visible',
};
const style2 = {
width: '300rpx',
height: '200rpx',
backgroundColor: 'green',
overflow: 'hidden',
};
return (
<View>
<View
style={{ height: '100rpx', width: '100rpx', backgroundColor: 'yellow' }} …
```
=> fix: setStyle does not update with `rpx`, in Weex

packages/rax/src/devtools/index.js
Rax 未来将会会通过`__RAX_DEVTOOLS_GLOBAL_HOOK__`这个全局变量来启用调试工具。
这样就可以避免和已有的react devtools发生冲突，毕竟rax已经无法和最新的react devtools v4.x版本兼容了。
我们基于react devtools v3.x版本开发出了[rax devtools](https://github.com/raxjs/rax-devtools)，功能目前和React Devtools v3.x 版本一样，不过未来会持续维护以保证与Rax相互兼容。
修改后的插件现在正在发布到Chrome商店的路上，估计审核还需要一定时间，审核通过之后就可以直接在商店搜索`Rax Developer Tools`来安装了
=> fix: use rax-devtools hooks instead of react devtools hooks

packages/jsx-compiler/src/modules/components.js, packages/jsx2mp-cli/__tests__/component.js, packages/jsx2mp-cli/demo/component.js
组件转成小程序代码时，会直接将 `import` 语句直接删掉，如果还有导出其他变量的话，会导致出错，应该只删除组件相关的变量
```js
import Loading, { showLoading, hideLoading } from 'loading';
=>
import { showLoading, hideLoading } from 'loading';
```
=> fix: remove all import specifiers of component

packages/jsx-compiler/src/modules/__tests__/jsx-plus.js, packages/jsx-compiler/src/modules/components.js, packages/jsx-compiler/src/modules/element.js, packages/jsx-compiler/src/modules/jsx-plus.js
```jsx
<View>
<View
x-for={(item1, index) in list}
style={{
width: "100rpx"
}}
>
<View x-for={(v, index) in item1}>
out: {index}
<Test val={v} />
</View>
</View>
</View>
```
compiled to
```jsx
<block a:for="{{_d0}}" a:for-item="item1" a:for-index="index">
<view style="{{_s0}}" class="__rax-view">
<block a:for="{{item1.item1}}" a:for-item="v" a:for-index="index0">
<view class="__rax-view">
out: {{ v.index0 }}
<c-89edce val="{{v.v}}" __parentId="{{__tagId}}" __tagId="5-{{index}}-{{index0}}" />
</view>
</block>
</view>
</block>
```
=> fix: nested loop render

packages/rax-set-native-props/package.json, packages/style-unit/README.md, packages/style-unit/package.json, packages/style-unit/src/__tests__/style-unit.js, packages/style-unit/src/__tests__/style-unit.miniApp.js, packages/style-unit/src/__tests__/style-unit.web.js, packages/style-unit/src/__tests__/style-unit.weex.js, packages/style-unit/src/index.js
Before: 
rax-set-native-props convert rpx to 'px' in web.
After:
rax-set-native-props convert rpx to 'vw' in web, same as driver-dom and driver-universal
=> feat: rax-set-native-props convert rpx to 'vw' in web.

packages/driver-dom/src/index.js
某些平台 (比如 kraken) 是没有 document 全局变量的, 这里直接做一个缓存是一个 side-effect, 会导致 JSEngine 抛出错误.  
改动方案体积对比: 
1. 对比增加一个 typeof 的判断, 增加的体积太多  
2. 不改动  
3. 改回 document (当前方案)  
直接使用 document 体积增加大约 0.002K 可以接受
=> fix: driver-dom not to interperate other platform

packages/rax-app/package.json, packages/rax-app/src/index.js, packages/rax-app/src/runApp.js
rax-app support custom driver. RunApp default driver is `driver-universal`.
```jsx
import { runApp } from 'rax-app';
import appConfig from './app.json';
import * as DriverDOM from 'driver-dom';
appConfig.driver = DriverDOM;
runApp(appConfig);
```
=> feat: rax-app support custom driver

packages/jsx2mp-runtime/src/component.js
When next data is null, `Object.keys(nextData)` will throw error
=> fix: nextData is null

packages/rax-app/package.json, packages/rax-app/src/runApp.js
For root not exists, rax will fallback to document.body automatically.
=> fix: remove root el detect at DOM tree

packages/jsx-compiler/src/modules/code.js, packages/jsx-compiler/src/modules/template.js, packages/jsx-compiler/src/utils/getExportComponentPath.js
1. Support use anonymous fn as component
```jsx
const Todo = () => {
return <View></View>
}
export default Todo;
```
2. Fix wrapper fn, like `handleComponent(Todo)`
```jsx
class Todo extends Component {
render() {
console.log(this.x);
return <View>Todo</View>;
}
}
function handleComponent(Com) {
Com.prototype.x = 1;
return Com;
}
export default handleComponent(Todo);
```
=> fix: jsx2mp template ast analyze

packages/jsx-compiler/src/modules/render-function.js
```jsx
class Parent extends Component {
handleClick() {
console.log('xxxx');
}
render() {
return <View onClick={() => this.handleClick()}>123</View>;
}
}
```
=> fix(jsx2mp): class method is not a render function

packages/jsx2mp-runtime/src/bridge.js, packages/jsx2mp-runtime/src/component.js
When the parent component does not pass `title`, child will render default value -- 'xxxx':
```jsx
export default class Child extends Component {
static defaultProps = {
title: 'xxxx'
};
render() {
return <View>{this.props.title}</View>;
}
}
```
=> feat(jsx2mp): support default props

packages/jsx-compiler/src/adapter.js, packages/jsx-compiler/src/modules/__tests__/rax-text.js, packages/jsx-compiler/src/modules/index.js, packages/jsx-compiler/src/modules/rax-text.js
In wechat miniprogram, slot couldn't in text component.
```jsx
<Text>123</Text> => <Text __content="{{123}}">123</Text>
```
=> chore(jsx2mp): compatible with rax-text in wechat miniprogram

packages/jsx-compiler/package.json, packages/jsx2mp-runtime/package.json, packages/jsx2mp-runtime/src/component.js
在支付宝小程序 component2 的模式下，更新一个对象的时候，小程序底层框架没有做数据合并，从而导致更新其中某一个 key 的时候，其它 key 变成 `undefined`
=> fix: update object data in component2

packages/jsx2mp-cli/getWebpackConfig.js, packages/jsx2mp-loader/src/component-loader.js, packages/jsx2mp-loader/src/page-loader.js, packages/jsx2mp-loader/src/utils/pathHelper.js
在构建跨平台应用程序时，希望重复使用尽可能多的代码，但是还是会出现代码有所不同的场景。
所以提了该PR，通过自动按平台引入特有后缀的文件，来实现平台扩展。
`阿里小程序`: .ali.js ...
`微信小程序`: .wechat.js ...
`百度`: .baidu.js ...
`头条`: .tt.js ...
扩展后缀和 [platformConfig](https://github.com/alibaba/rax/blob/master/packages/jsx2mp-cli/utils/platformConfig.js) 的key一致
=> feat: import platform specific extensions

packages/jsx-compiler/package.json, packages/jsx-compiler/src/modules/components.js, packages/jsx-compiler/src/modules/jsx-plus.js
当 `x-slot` 模板被容器循环渲染的时候，模板本身在编译时不知道自己被循环，导致 `tagId` 重复，从而渲染异常
=> fix: x-slot render

packages/driver-universal/package.json, packages/driver-universal/src/index.js
Since driver-miniapp use `export default` to export, driver-universal should import it correspondingly.
=> fix(driver-universal): import driver-miniapp by mistake

packages/jsx2mp-runtime/package.json, packages/jsx2mp-runtime/src/adapter/getNativeEventBindTarget.js, packages/jsx2mp-runtime/src/component.js, packages/jsx2mp-runtime/src/cycles.js, packages/jsx2mp-runtime/src/hooks.js, packages/jsx2mp-runtime/src/index.js, packages/jsx2mp-runtime/src/nativeEventListener.js, packages/jsx2mp-runtime/src/page.js, packages/jsx2mp-runtime/src/pageInstanceMap.js
小程序原生生命周期 break change:
- 移除在 class component 上注册监听
- 移除大量小程序专属的 hooks，如 usePageAppShare, useLocation
- 支持通过 `addNativeEventListener` `removeNativeEventListener` 等更加灵活的处理原生事件
=> refactor(jsx2mp): native event bind

packages/jsx-compiler/package.json, packages/jsx-compiler/src/modules/__tests__/jsx-plus.js, packages/jsx-compiler/src/modules/__tests__/list.js, packages/jsx-compiler/src/modules/code.js, packages/jsx-compiler/src/modules/condition.js, packages/jsx-compiler/src/modules/element.js, packages/jsx-compiler/src/modules/jsx-plus.js, packages/jsx-compiler/src/modules/list.js, packages/jsx-compiler/src/utils/createIncrement.js, packages/jsx-compiler/src/utils/createListIndex.js, packages/jsx-compiler/src/utils/handleList.js, packages/jsx-compiler/src/utils/handleListProps.js, packages/jsx-compiler/src/utils/handleListStyle.js, packages/jsx-compiler/src/utils/handleParentListReturn.js, packages/jsx2mp-runtime/src/component.js
- 支持在 `map` 函数中定义的表达式里使用循环产生的临时变量 `item`/ `index`
- 支持 `x-for` 和 `x-if` 混合使用的场景下，`x-if` 的判断条件中包含循环产生的临时变量
- 支持在循环中使用 `ref` 的功能
- 修复层级循环时动态绑定的数据赋值出错的问题，如：
```jsx
<Fragment x-for={(item, index) in data} x-if={item}>
<Text x-for={(benefitItem, index) in item.b} />
</Fragment>
``` 
`map` 中 `return` 出来的值应该是：
```js
item: {
...item,
b: item.b.map(() => {});
}
```
=> Feat(jsx2mp): list render

packages/jsx2mp-runtime/src/bridge.js, packages/jsx2mp-runtime/src/router.js, packages/jsx2mp-runtime/src/updater.js
- 组件绑定属性的表现和 `rax core` `react` 保持一致，即 `functional component` 无法通过 `Todo.defaultProps` 来设置属性，也无法通过 `Todo.prototype.xxx` 给组件实例绑定属性
- 修复 `withRouter` 中 `history` `location` 在函数组件上的绑定问题，并且优先级保持最高，避免被覆盖
=> fix(jsx2mp): history & location should be hightest level

packages/driver-dom/package.json, packages/driver-dom/src/__tests__/css-custom-properties.js, packages/driver-dom/src/__tests__/css-unit-operations.js, packages/driver-dom/src/__tests__/event-listener.js, packages/driver-dom/src/__tests__/node-operations.js, packages/driver-dom/src/__tests__/svg.js, packages/driver-dom/src/index.js, packages/driver-miniapp/package.json, packages/driver-miniapp/src/index.js
Add `__shouldTransformRpx` to avoid `rpx2vw`
=> chore: add parameter control rpx to vw

packages/jsx-compiler/src/adapter.js, packages/jsx-compiler/src/modules/__tests__/attribute.js, packages/jsx-compiler/src/modules/__tests__/jsx-plus.js, packages/jsx-compiler/src/modules/attribute.js, packages/jsx-compiler/src/modules/jsx-plus.js, packages/jsx-compiler/src/modules/list.js, packages/jsx-compiler/src/utils/handleList.js, packages/jsx-compiler/src/utils/handleListJSXExpressionContainer.js, packages/jsx-compiler/src/utils/handleParentListReturn.js
- 支持微信小程序循环 `key` 的设置方式
- 修复循环渲染中，需要渲染对象上某个属性的时候只处理了第一个值的问题
=> fix: loop key

packages/jsx-compiler/src/modules/code.js, packages/jsx-compiler/src/modules/template.js, packages/jsx-compiler/src/utils/__tests__/isClassComponent.js, packages/jsx-compiler/src/utils/isClassComponent.js, packages/jsx2mp-runtime/src/bridge.js
1. 支持 class component 的继承用法，即 `class A extends Component {}; export default class Home extends A {}`
2. 支持导出一个匿名的 class component，即 `export default class extends Component`
3. 支持通过赋值的方式定义一个 class  component，即 `const Home = class extends Component{}; export default Home;`
=> feat(jsx2mp): support more class component usage

packages/rax-pwa/package.json, packages/rax-pwa/src/Navigation/index.js
Fix alive page history change to a common page, useEffect method will be called.
```jsx
import { createElement, useEffect } from 'rax';
export default function Home(props) {
useEffect(() => {
// called when history change to the page not alive. Like page1
}, []);
return (
....
);
}
```
Example app.json
```json
// app.json
{
"routes": [
{
"path": "/",
"keepAlive": true,
"source": "pages/Home/index"
},
{
"path": "/page1",
"source": "pages/Page1/index"
}
]
}
```
=> Fix alive page useEffect triggered by history

packages/jsx-compiler/package.json, packages/jsx-compiler/src/modules/element.js
Support:
```js
const someObject = {info: 'xxxxx'};
const info = 'info';
```
```jsx
<View>someObject[info]</View>
```
=> feat(jsx2mp): support computed memberepxression

packages/jsx-compiler/src/modules/__tests__/list.js, packages/jsx-compiler/src/modules/condition.js, packages/jsx-compiler/src/modules/jsx-plus.js, packages/jsx-compiler/src/modules/list.js, packages/jsx-compiler/src/parser/index.js, packages/jsx-compiler/src/utils/getParentListPath.js, packages/jsx-compiler/src/utils/handleParentListReturn.js, packages/jsx2mp-runtime/src/bridge.js, packages/jsx2mp-runtime/src/router.js
- `history` 传参用法对齐 web/weex
- 支持更多循环使用场景，详情见测试用例
- 合并 `$slotsScoped` 到 `$slots`
- 修复 if 渲染问题
=> feat(jsx2mp): support more usage in list render

packages/rax-create-portal/src/__tests__/createPortal.js, packages/rax/src/vdom/instance.js
portal new context的传递需要parent instance
=> fix: portal with new context

packages/rax/src/vdom/__tests__/fragment.js, packages/rax/src/vdom/fragment.js, packages/rax/src/vdom/native.js
fragment的native node 应该类似 composite 一样，应该是个只读的操作
之前的代码都是自上往下考虑 fragment的native node节点
但是fragment本身并不清楚子节点自身更新带来的native node的变化，从而造成内存泄露和bug
=> fix: fragment cache native node

packages/rax/src/__tests__/hooks.js, packages/rax/src/hooks.js
unmount时候，use effect的destory 需要同步进行执行
不然可能和 layout effect可能产生时间差，造成bug
```js
Child() {
useEffect(() => {
event.on(setState);
return () => {
event.off(setState);
}
})
}
App () {
useLayout() {
event.emit()
}
return type === 1 ? <<Child /> : null
}
```
比如上面，当前渲染中，child 可能已经卸载了，但是先执行app的 useLayout 触发了卸载的child的 setState
=> fix: destory function of a passive effect should call synchronously

packages/rax/package.json, packages/rax/src/__tests__/hooks.js, packages/rax/src/hooks.js
=> release rax@1.1.3

packages/jsx2mp-runtime/src/bridge.js, packages/jsx2mp-runtime/src/component.js, packages/jsx2mp-runtime/src/hooks.js
解决的问题是，加上 `memo` 之后，组件的 `shouldComponentUpdate ` 方法会默认添加 props 的浅对比来避免父组件重新渲染的时候，子组件也被重新渲染。但是会导致，函数组件自身状态发生更新时，也被这个条件拦下来，导致组件没有重新渲染。
=> fix(jsx2mp): memo update

packages/jsx2mp-runtime/src/adapter/getComponentBaseConfig.js
- 设置微信端自定义组件样式和页面样式互相影响，表现与支付宝小程序对齐
=> fix(jsx2mp): style isolated in component in wechat

packages/jsx2mp-runtime/src/bridge.js
1. 页面 `unmount` 执行销毁实例方法时添加兜底
2. 修复绑定事件传递 `event` 对象时，出现漏传的问题
=> fix(jsx2mp): event params pass

packages/jsx-compiler/package.json, packages/jsx-compiler/src/adapter.js, packages/jsx-compiler/src/modules/__tests__/attribute.js, packages/jsx2mp-runtime/package.json, packages/jsx2mp-runtime/src/adapter/getComponentBaseConfig.js, packages/jsx2mp-runtime/src/bridge.js, packages/jsx2mp-runtime/src/component.js
- 修复支付宝、微信小程序各自数据更新时潜在的 bug
- 修复支付宝小程序列表 key 值编译成 a:key 不生效的问题
- 设置微信端自定义组件样式和页面样式互相影响，表现与支付宝小程序对齐
- 修复微信端 rax-view/rax-text 上点击事件失效的 bug
- 页面 unmount 执行销毁实例方法时添加兜底
- 修复绑定事件传递 event 对象时，出现漏传的问题
=> [RELEASE] jsx2mp @0608

packages/driver-dom/package.json, packages/driver-dom/src/__tests__/hydrate.js, packages/driver-dom/src/index.js, packages/driver-dom/src/warning.js, packages/rax-server-renderer/package.json, packages/rax-server-renderer/src/__tests__/elements.js, packages/rax-server-renderer/src/__tests__/form.js, packages/rax-server-renderer/src/__tests__/hooks.js, packages/rax-server-renderer/src/__tests__/lifecycle.js, packages/rax-server-renderer/src/__tests__/renderToString.js, packages/rax-server-renderer/src/index.js
Fix：https://github.com/alibaba/rax/issues/1883
Add comment tag ``  between sibling text node to avoid hydrate error. 
When rendering such a Component:
```jsx
<div>{year}{month}{date}</div>
```
The HTML string after SSR is:
```html
<div>20200521</div>
```
When hydrate the `month`, it will find the text node after `` to compare text, instand of create a new text node.
The child nodes of div after hydrate is:
```json
[
"2020",
"",
"05",
"",
"21"
]
```
=> fix: sibling text node hydrating error

packages/miniapp-render/src/createConfig/element.js
页面根节点通过自定义组件渲染，从而避免在使用到原生组件时，将 `root.axml` 每次都写入每个页面造成小程序体积过大
=> chore(miniapp): root node use custom component

packages/driver-dom/package.json, packages/driver-dom/src/__tests__/attributes.js, packages/driver-dom/src/__tests__/svg.js, packages/driver-dom/src/index.js
When set some attribute such as 'transform'  to DOM by `node[propKey] = propValue`,  it will fail and do not throw error in none strict mode.
=> Fix failure to set attribute by DOM properties

packages/driver-dom/package.json, packages/driver-dom/src/__tests__/hydrate.js, packages/driver-dom/src/index.js
When hydrate node with  dangerouslySetInnerHTML :
```jsx
<div className="container" dangerouslySetInnerHTML={{__html: `<div>About Rax</div><div>Docs</div>`}} />
```
It will trigger `recolectHydrationChild`  and clear innerHtml.
Result is `<div class="container"></div>` rather than `<div class="container" ><div>About Rax</div><div>Docs</div></div>`
=> Fix: hydrate node with dangerouslySetInnerHTML

packages/miniapp-render/src/node/root.js
在判断父节点是否已经在视图中渲染的逻辑中，应该 cache 的是通过 `_internal.data` 获取到的值，而不是本次更新需要更新的值，具体见代码变更。
=> fix(miniapp): path cache

packages/jsx-compiler/src/constants.js, packages/jsx-compiler/src/modules/components.js, packages/jsx-compiler/src/parser/index.js, packages/miniapp-render/src/createConfig/element.js, packages/miniapp-render/src/document.js, packages/miniapp-render/src/node/element/custom-component.js, packages/miniapp-render/src/node/root.js, packages/miniapp-render/src/utils/cache.js
=> feat(miniapp): support using miniapp plugins

packages/jsx-compiler/src/adapter.js, packages/jsx-compiler/src/modules/__tests__/element.js, packages/jsx-compiler/src/modules/element.js
针对支付宝小程序，当直接使用 `props.a` 或者 `this.props.a` 在模板中渲染的时候，避免进行动态编译绑定，大幅减少子组件每次渲染进行 `setData` 时的数据传输量
=> chore(jsx2mp): render directly using props

packages/miniapp-render/src/utils/cache.js
- 无论是否有已创建的自定义组件 element，当有新的自定义组件事件设置时，都应该储存至 elementMethodsCache。否则后续有新的 element 创建时，会出现事件丢失的情况
=> fix(miniapp): miss methods binded to element

packages/driver-universal/package.json, packages/driver-universal/src/index.js
在一些 SSR 场景下，如果共用入口，会引入 driver-universal, 虽然没执行但会直接抛错，阻断了后续流程
=> fix: should not throw error by default

packages/miniapp-render/src/builtInComponents/swiper.js
=> fix(miniapp): not distinguish swiper onAnimationEnd  event between alipay and wechat

packages/jsx2mp-runtime/package.json, packages/jsx2mp-runtime/src/updater.js
修复微信小程序通过 `updateChildProps` 获取父组件传递过来的 `props` 的时候，要晚于组件实例创建，导致 `constructor` 阶段无法拿到预期的 `props`
=> fix(jsx2mp): wechat miniprogram constructor props receive

packages/driver-dom/CHANGELOG.md, packages/driver-dom/package.json, packages/driver-dom/src/index.js
iOS 10 下，对节点增加 `transition-timing-function` 的样式，会同时追加 `-webkit-transition-timing-function` 属性。同样的，删除其中一个样式属性，另外一个也会被随之删除。在 Hydrate 样式的时候，会因为拿到的样式名为 undefined ，导致执行错误，所以需要增加兼容处理。
=> Fix hydrate style in iOS 10

packages/rax/src/vdom/__tests__/composite.js, packages/rax/src/vdom/performInSandbox.js
Fix bug: [The input argument of getDerivedStateFromError of class component is missing #2211
](https://github.com/alibaba/rax/issues/2211)
=> fix(rax): add lacked input argument of getDerivedStateFromError (fix #2211)

packages/rax/CHANGELOG.md, packages/rax/package.json, scripts/dist-core.js
The wrong result: https://unpkg.alibaba-inc.com/browse/rax@1.2.1/lib/compat/index.js
The expected result: https://unpkg.alibaba-inc.com/browse/rax@1.2.2-beta.2/lib/compat/index.js
=> fix: compat react bundle path

.github/workflows/auto-publisher.yml, .github/workflows/bench.yml, .github/workflows/ci.yml, packages/rax/src/types.js, packages/rax/src/vdom/__tests__/empty.js, packages/rax/src/vdom/shouldUpdateComponent.js, scripts/bench/package.json
Replay code:
```js
import { createElement, render, useState, Fragment } from 'rax';
import Driver from 'driver-universal';
let index = 0;
function Home() {
const [arr, setArr] = useState([1, 2, 3, 4, 5, 6]);
function click() {
switch (index) {
case 0:
setArr([4, 5, 6]);
break;
case 1:
setArr([1]);
break;
default:
break;
}
index++;
}
return (
<div onClick={click}>
{new Array(6).fill(1).map((v, index) => (
<Fragment key={index}>{arr[index]}</Fragment>
))}
</div>
);
}
render(<Home />, document.getElementById('root'), { driver: Driver });
```
More simple case, u can see the added test cases.
=> chore: avoid update falsy node
